/* §61/93، Addendum §56–72: runner واقعی، نه updateِ دلخواهِ status. */
import {lookup} from 'node:dns/promises';
import {request as httpsRequest} from 'node:https';
import {isIP} from 'node:net';
import {createHash} from 'node:crypto';
import nodemailer from 'nodemailer';
import {createIndexNowAdapter} from '@petavu/seo';
import {signBody} from '@petavu/security';
import {uuidv7,type Env,type Logger} from '@petavu/shared';
import type {SqlClient,Row} from '@petavu/db';
import {measurePage} from '@petavu/design/measure';
import {publicDesignPath} from '@petavu/design/pipeline';
export interface Job extends Row{id:string;kind:string;payload:Record<string,unknown>;business_id:string|null;lease_id:string;locked_by:string;request_id:string|null;attempts:number}
export interface Rendered {status:number;headers:Record<string,string>;body:string;bytes?:Buffer}
export interface WorkerOptions {client:SqlClient;env:Env;logger:Logger;workerId?:string;render?:(path:string)=>Promise<Rendered>;secrets?:Readonly<Record<string,string|undefined>>;fetch?:typeof fetch;allowLocalTestDestinations?:boolean}
const CORE=new Set(['event.dispatch','seo.metadata_rebuild','search.index_content','search.index_business','search.reindex','seo.sitemap_rebuild','seo.structured_data_rebuild','seo.ai_rebuild','performance.rollup','ops.maintenance']);
export const WORKER_KINDS=[...CORE,'design.monitor','notification.deliver','webhook.deliver','seo.indexnow_submit'] as const;
class JobFailure extends Error{constructor(readonly code:string,readonly evidence:Record<string,unknown>={}){super(code);}}
function errorCode(error:unknown):string{return error instanceof JobFailure?error.code:error instanceof Error?error.name+':'+error.message.slice(0,150):'job_error';}
function privateAddress(value:string):boolean{return value==='::1'||value.startsWith('fc')||value.startsWith('fd')||value.startsWith('fe80')||/^127\.|^10\.|^0\.|^169\.254\.|^192\.168\.|^172\.(?:1[6-9]|2\d|3[01])\./.test(value);}
export async function assertPublicDestination(raw:string,allowLocal=false):Promise<URL>{const url=new URL(raw);if(url.protocol!=='https:'||url.username||url.password)throw new JobFailure('unsafe_destination');const addresses=isIP(url.hostname)?[{address:url.hostname}]:await lookup(url.hostname,{all:true});if(!addresses.length||(!allowLocal&&addresses.some(a=>privateAddress(a.address))))throw new JobFailure('unsafe_destination');return url;}
export async function postPinnedWebhook(url:URL,body:string,headers:Record<string,string>,timeoutMs:number,allowLocal=false):Promise<{status:number}>{
 const addresses=isIP(url.hostname)?[{address:url.hostname,family:isIP(url.hostname)}]:await lookup(url.hostname,{all:true});if(!addresses.length||(!allowLocal&&addresses.some(a=>privateAddress(a.address))))throw new JobFailure('unsafe_destination');const address=addresses[0]!;
 return new Promise((resolve,reject)=>{const req=httpsRequest(url,{method:'POST',agent:false,headers:{...headers,'content-length':String(Buffer.byteLength(body))},timeout:timeoutMs,lookup:(_host,_options,callback)=>callback(null,address.address,address.family)},res=>{res.resume();resolve({status:res.statusCode??502});});req.on('timeout',()=>req.destroy(new Error('webhook_timeout')));req.on('error',reject);req.end(body);});
}
export function createWorker(options:WorkerOptions){const {client,env,logger}=options;const workerId=options.workerId??'worker-'+uuidv7();let stopped=false,running=false;const query=async<T extends Row=Row>(text:string,params:readonly unknown[]=[])=>client.withTransaction(tx=>tx.asRole('pv_worker',async c=>(await c.query<T>(text,params)).rows));
 async function monitor(job:Job):Promise<Record<string,unknown>>{const [material]=await query<{data:Record<string,unknown>}>('select ops.delivery_material($1,$2,$3) data',[job.id,workerId,job.lease_id]);const data=material?.data??{};if(data['not_applicable'])return data;if(!options.render)throw new JobFailure('renderer_not_configured');const reports=[];let passed=true;for(const p of data['pages'] as Array<{key:string}>){const path=publicDesignPath(p.key,data['business_slug'] as string|null);const measured=await measurePage({path,origin:env.origins.public,fetch:async(resource)=>{const r=await options.render!(resource);return {status:r.status,contentType:r.headers['content-type']??'text/html',bytes:r.bytes??Buffer.from(r.body)};}});const [checked]=await query<{budget:Record<string,unknown>}>('select ops.check_budget($1,$2::jsonb) budget',[path,JSON.stringify(measured.measurement)]);if(checked?.budget['verdict']!=='pass'||measured.failed.length)passed=false;reports.push({path,delivery:measured,budget:checked?.budget});}const proof={passed,hash:data['hash'],pages:reports,cwv:'not_compared_without_browser_samples',measured_at:new Date().toISOString()};await query('select ops.monitor_report($1,$2,$3,$4::jsonb)',[job.id,workerId,job.lease_id,JSON.stringify(proof)]);if(!passed)throw new JobFailure('delivery_budget_breach',proof);return proof;}
 async function deliver(job:Job):Promise<Record<string,unknown>>{const [row]=await query<{data:Record<string,unknown>}>('select ops.delivery_material($1,$2,$3) data',[job.id,workerId,job.lease_id]);const data=row?.data??{};if(data['not_applicable'])return data;
 if(job.kind==='notification.deliver'){const n=data['notification'] as Record<string,unknown>;const channel=n['channel'];if(channel==='in_app'){await query('select ops.execute_core_job($1,$2,$3)',[job.id,workerId,job.lease_id]);return {channel:'in_app',delivered:true,notification_id:n['id']};}if(channel!=='email')throw new JobFailure('adapter_not_configured',{channel});const e=options.secrets??process.env;if(env.email.driver!=='smtp'||!e['SMTP_HOST']||!e['SMTP_FROM']||!data['email'])throw new JobFailure('email_not_configured',{driver:env.email.driver,reason:!data['email']?'verified_recipient_missing':'SMTP configuration required'});const transport=nodemailer.createTransport({host:e['SMTP_HOST'],port:Number(e['SMTP_PORT']??465),secure:e['SMTP_SECURE']!=='false',auth:e['SMTP_USER']?{user:e['SMTP_USER'],pass:e['SMTP_PASSWORD']}:undefined,connectionTimeout:10000,socketTimeout:15000});try{const result=await transport.sendMail({from:e['SMTP_FROM'],to:String(data['email']),subject:String(n['title']),text:String(n['body']??''),messageId:`<${job.id}@petavu.invalid>`});if(!result.accepted.length)throw new JobFailure('email_not_accepted');await query('select ops.delivery_result($1,$2,$3,true)',[job.id,workerId,job.lease_id]);return {channel:'email',accepted:true,message_id:result.messageId};}finally{transport.close();}}
 const endpoint=data['endpoint'] as Record<string,unknown>,delivery=data['delivery'] as Record<string,unknown>;const ref=String(endpoint['secret_ref']);const secret=/^WEBHOOK_SECRET_[A-Z0-9_]+$/.test(ref)?(options.secrets??process.env)[ref]:undefined;if(!secret||secret.length<32)throw new JobFailure('webhook_secret_not_configured');const url=await assertPublicDestination(String(endpoint['url']),env.isTest&&options.allowLocalTestDestinations===true);const timestamp=Math.floor(Date.now()/1000),body=JSON.stringify(delivery['payload']);const signature=signBody(secret,`${timestamp}.${delivery['id']}.${body}`);const headers={'content-type':'application/json','x-petavu-delivery':String(delivery['id']),'x-petavu-timestamp':String(timestamp),'x-petavu-signature':signature,'idempotency-key':String(delivery['id'])};const response=options.fetch?await options.fetch(url,{method:'POST',redirect:'error',signal:AbortSignal.timeout(Math.min(Number(endpoint['timeout_ms']),15000)),headers,body}):await postPinnedWebhook(url,body,headers,Math.min(Number(endpoint['timeout_ms']),15000),env.isTest&&options.allowLocalTestDestinations===true);const ok=response.status>=200&&response.status<300;await query('select ops.delivery_result($1,$2,$3,$4,$5,$6)',[job.id,workerId,job.lease_id,ok,response.status,ok?null:'http_'+response.status]);if(!ok)throw new JobFailure('webhook_http_'+response.status);return {delivered:true,status:response.status,body_hash:createHash('sha256').update(body).digest('hex')};}
 async function indexnow(job:Job):Promise<Record<string,unknown>>{const [row]=await query<{data:Record<string,unknown>}>('select ops.indexing_material($1,$2,$3) data',[job.id,workerId,job.lease_id]);const data=row?.data??{},config=(data['config']??{}) as Record<string,unknown>;if(config['enabled']!==true||typeof config['key']!=='string')throw new JobFailure('indexnow_not_configured');const paths=data['paths'] as string[];const adapter=createIndexNowAdapter({key:config['key'],baseUrl:env.origins.public,maxAttempts:1,...(options.fetch?{fetch:options.fetch}:{})});const results=await adapter.submit(paths.map(p=>env.origins.public+p));for(const result of results){await query('select ops.indexing_result($1,$2,$3,$4::jsonb)',[job.id,workerId,job.lease_id,JSON.stringify(result)]);if(!['sent','accepted'].includes(result.status))throw new JobFailure('indexnow_'+result.status,{result});}return{results,submitted_paths:paths.length};}
 async function execute(job:Job){try{let result:Record<string,unknown>;if(CORE.has(job.kind)){const [row]=await query<{result:Record<string,unknown>}>('select ops.execute_core_job($1,$2,$3) result',[job.id,workerId,job.lease_id]);result=row?.result??{};}else if(job.kind==='seo.indexnow_submit')result=await indexnow(job);else if(job.kind==='design.monitor')result=await monitor(job);else if(['notification.deliver','webhook.deliver'].includes(job.kind))result=await deliver(job);else throw new JobFailure('handler_not_registered',{kind:job.kind});await query('select ops.finish_owned($1,$2,$3,true,$4::jsonb)',[job.id,workerId,job.lease_id,JSON.stringify(result)]);logger.info('کار اجرا شد',{jobId:job.id,kind:job.kind,requestId:job.request_id,workerId});return {id:job.id,succeeded:true,result};}catch(error){const code=errorCode(error);const evidence=error instanceof JobFailure?error.evidence:{};if(['notification.deliver','webhook.deliver'].includes(job.kind)&&/not_configured/.test(code))await query('select ops.delivery_result($1,$2,$3,false,null,$4)',[job.id,workerId,job.lease_id,code]);await query('select ops.finish_owned($1,$2,$3,false,$4::jsonb,$5)',[job.id,workerId,job.lease_id,JSON.stringify({code,...evidence}),code]);logger.warn('کار موفق نبود',{jobId:job.id,kind:job.kind,requestId:job.request_id,workerId,code});return {id:job.id,succeeded:false,result:{code,...evidence}};}}
 async function tick(limit=10){if(running)return{skipped:true};running=true;try{const [setup]=await query('select ops.dispatch_outbox(50) dispatched,ops.schedule_due() scheduled,ops.queue_deliveries() deliveries');const jobs=await query<Job>('select id,kind,payload,business_id,lease_id,locked_by,request_id,attempts from ops.claim_leased($1,$2)',[workerId,limit]);const outcomes=[];for(const job of jobs)outcomes.push(await execute(job));return {workerId,setup,jobs:outcomes};}finally{running=false;}}
 return {workerId,tick,execute,stop(){stopped=true;},async run(pollMs=1000){while(!stopped){await tick();await new Promise<void>(resolve=>setTimeout(resolve,pollMs));}}};}
