import { test, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { createFixture, HOSTS } from '../scripts/lib/fixture.mjs';
import { ADMIN_SECTIONS } from '../apps/web/dist/panel/admin.js';
let f, admin, member, cookie, csrf, ordinaryCookie, ordinaryCsrf, business;
const origin=`http://${HOSTS.admin}`;
async function login(user){const r=await fetch(f.api.url+'/api/v1/auth/login',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify({identifier:user.email,password:user.password})});const json=await r.json();assert.equal(r.status,200,JSON.stringify(json));return {cookie:r.headers.getSetCookie().map(v=>v.split(';')[0]).join('; '),csrf:json.csrf_token};}
async function api(path,method='GET',body,ordinary=false){const r=await fetch(f.api.url+path,{method,headers:{origin,cookie:ordinary?ordinaryCookie:cookie,'x-csrf-token':ordinary?ordinaryCsrf:csrf,'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});return{status:r.status,json:await r.json()};}
before(async()=>{f=await createFixture({api:true});admin=await f.registerUser({email:'admin@example.test'});member=await f.registerUser({email:'ordinary@example.test'});await f.sudo("insert into auth.user_platform_role(user_id,role_key) values($1,'superadmin')",[admin.userId]);({cookie,csrf}=await login(admin));({cookie:ordinaryCookie,csrf:ordinaryCsrf}=await login(member));business=await f.createBusiness({slug:'admin-private',name:'بازبینی واقعی',ownerUserId:member.userId,status:'draft',visibility:'private'});}, {timeout:60000});
after(async()=>await f?.close());
test('28 admin items are DB data, all ready items have a section',async()=>{const r=await api('/api/v1/panel/menu?surface=admin');assert.equal(r.status,200);assert.equal(r.json.items.length,28);for(const item of r.json.items.filter(v=>v.availability==='ready'))assert.ok(ADMIN_SECTIONS[item.key],item.key);});
for(const key of Object.keys(ADMIN_SECTIONS)) test(`admin ${key} renders real data through API`,async()=>{const path=key==='dashboard'?'/app':`/app/${key.replaceAll('_','-')}`;const page=await f.page(path,{host:HOSTS.admin,headers:{cookie}});assert.equal(page.status,200,`${key} ${page.body.slice(-1100)}`);assert.match(page.body,/panel-body--admin/);assert.match(page.headers['cache-control'],/no-store/);});
for(const path of ['/users','businesses','content','taxonomy','roles','seo','redirects','indexing','jobs','automation','performance','security','audit','backups','retention','settings'].map(v=>'/api/v1/admin/'+v.replace(/^\//,'')))test(`ordinary actor denied ${path}`,async()=>{assert.equal((await api(path,'GET',undefined,true)).status,403);});
test('ordinary identity cannot access admin surface',async()=>{const page=await f.page('/app',{host:HOSTS.admin,headers:{cookie:ordinaryCookie}});assert.equal(page.status,403);assert.ok(!page.body.includes('بازبینی واقعی'));});
test('safe user response never contains identifiers, credentials or session secrets',async()=>{const r=await api('/api/v1/admin/users');assert.equal(r.status,200);const text=JSON.stringify(r.json);for(const secret of ['secret_hash','password_hash','value_key','admin@example.test','ordinary@example.test'])assert.ok(!text.includes(secret));});
test('admin cursor has stable distinct pages',async()=>{const a=await api('/api/v1/admin/users?limit=1');assert.equal(a.status,200);assert.equal(a.json.items.length,1);assert.ok(a.json.nextCursor);const b=await api(`/api/v1/admin/users?limit=1&cursor=${encodeURIComponent(a.json.nextCursor)}`);assert.equal(b.status,200);assert.notEqual(a.json.items[0].id,b.json.items[0].id);});
test('bad cursor cannot turn into SQL',async()=>{assert.equal((await api('/api/v1/admin/users?cursor=%27%20or%201%3D1')).status,400);});
test('business state cannot change without recent authentication',async()=>{const [current]=await f.sudo('select version from app.business where id=$1',[business]);const r=await api(`/api/v1/admin/businesses/${business}/state`,'POST',{expected_version:current.version,to:'active',reason:'بازبینی کامل'});assert.equal(r.status,403);});
test('wrong re-auth password does not mark session as fresh',async()=>{assert.equal((await api('/api/v1/auth/reauth','POST',{password:'incorrect'})).status,401);});
test('real password re-auth unlocks audited, versioned moderation',async()=>{assert.equal((await api('/api/v1/auth/reauth','POST',{password:admin.password})).status,200);const [current]=await f.sudo('select version from app.business where id=$1',[business]);const r=await api(`/api/v1/admin/businesses/${business}/state`,'POST',{expected_version:current.version,to:'active',reason:'بررسی واقعی'});assert.equal(r.status,200,JSON.stringify(r.json));assert.equal(r.json.result.status,'active');assert.equal((await api(`/api/v1/admin/businesses/${business}/state`,'POST',{expected_version:current.version,to:'suspended',reason:'قدیمی'})).status,409);const [audit]=await f.sudo("select count(*)::int n from ops.audit_log where action='business.state_changed' and entity_id=$1",[business]);assert.equal(audit.n,1);});
test('unsafe state edge rejected and no partial record',async()=>{const [current]=await f.sudo('select version from app.business where id=$1',[business]);assert.equal((await api(`/api/v1/admin/businesses/${business}/state`,'POST',{expected_version:current.version,to:'draft',reason:'غیرمجاز'})).status,412);});
test('data-driven new business type is immediately available to public API',async()=>{const r=await api('/api/v1/admin/taxonomy','POST',{key:'admin_new_trade',name_fa:'صنف افزوده از API'});assert.equal(r.status,201,JSON.stringify(r.json));const list=await api('/api/v1/catalog/business-types');assert.ok(list.json.types.some(v=>v.key==='admin_new_trade'));});
test('global settings reject stale revision and mask secrets',async()=>{const settings=await api('/api/v1/admin/settings');const item=settings.json.items.find(v=>!v.is_secret);const r=await api(`/api/v1/admin/settings/${encodeURIComponent(item.key)}`,'PUT',{expected_version:item.version,value:item.value});assert.equal(r.status,200);assert.equal((await api(`/api/v1/admin/settings/${encodeURIComponent(item.key)}`,'PUT',{expected_version:item.version,value:item.value})).status,409);});
test('authenticated member cannot invoke safe definer user list directly',async()=>{await assert.rejects(()=>f.asRole('pv_app','select id,display_name from app.admin_users(null,2)',[],{'app.user_id':member.userId}),e=>e.code==='42501');});
