import {test,before,after} from 'node:test';import assert from 'node:assert/strict';import {createFixture,HOSTS} from '../scripts/lib/fixture.mjs';import {createWorker} from '../apps/worker/dist/index.js';import {fetchGsc,fetchBing,remoteSearchAdapter} from '../packages/seo/dist/index.js';import {silentLogger} from '../packages/shared/dist/index.js';
let f,owner,admin,business,privateBusiness,content,cookie,csrf;const origin=`http://${HOSTS.admin}`;
async function api(path,method='GET',body){const r=await fetch(f.api.url+'/api/v1'+path,{method,headers:{origin,cookie,'x-csrf-token':csrf,'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});return{status:r.status,json:await r.json()};}
before(async()=>{f=await createFixture({api:true});owner=await f.registerUser({email:'discover-owner@example.test'});admin=await f.registerUser({email:'discover-admin@example.test'});await f.sudo("insert into auth.user_platform_role(user_id,role_key) values($1,'superadmin')",[admin.userId]);business=await f.createBusiness({slug:'discovery-public',name:'كلينيك روشن سرچ',ownerUserId:owner.userId});privateBusiness=await f.createBusiness({slug:'discovery-private',name:'سرچ راز شرکت',ownerUserId:owner.userId,status:'draft',visibility:'private'});content=await f.createContent({businessId:business,slug:'source-article',title:'مقاله سلامت مستند',summary:'داده واقعی'});await f.sudo('update app.content set body_text=$1 where id=$2',['شرح مستند خدمات و اطلاعات عمومی '.repeat(20),content]);await f.asRole('pv_worker','select seo.refresh_search_scope($1)',[business]);await f.asRole('pv_worker','select seo.refresh_search_scope($1)',[privateBusiness]);const r=await fetch(f.api.url+'/api/v1/auth/login',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify({identifier:admin.email,password:admin.password})});const j=await r.json();cookie=r.headers.getSetCookie().map(v=>v.split(';')[0]).join('; ');csrf=j.csrf_token;},{timeout:60000});after(async()=>await f?.close());
test('native FTS normalizes Persian and Arabic letters',async()=>{const r=await api('/discovery/search?q='+encodeURIComponent('کلینیک'));assert.equal(r.status,200,JSON.stringify(r.json));assert.ok(r.json.results.some(v=>v.entity_id===business));assert.equal(r.json.adapter.state,'configured');});
test('content and business are independently searchable with actual canonical paths',async()=>{const r=await api('/discovery/search?q='+encodeURIComponent('سلامت')+'&kind=content');assert.equal(r.status,200);assert.ok(r.json.results.some(v=>v.path==='/b/discovery-public/c/source-article'));assert.ok(r.json.results.every(v=>v.entity_kind==='content'));});
test('private tenant content never enters a public search response',async()=>{const r=await api('/discovery/search?q='+encodeURIComponent('راز'));assert.equal(r.status,200);assert.equal(r.json.results.length,0);});
test('stale index cannot expose content after privacy/source-version change',async()=>{await f.sudo("update app.business set visibility='private' where id=$1",[business]);const r=await api('/discovery/search?q='+encodeURIComponent('کلینیک'));assert.ok(!r.json.results.some(v=>v.entity_id===business));const rows=await f.asRole('pv_public','select title from seo.search_document where entity_id=$1',[business]);assert.equal(rows.length,0);await f.sudo("update app.business set visibility='public' where id=$1",[business]);await f.asRole('pv_worker','select seo.refresh_search_scope($1)',[business]);});
test('zero-result query generates an idempotent opportunity, not an invented page',async()=>{const query='نیازمحتوایخاصزیناسب';for(let i=0;i<2;i++)assert.equal((await api('/discovery/search?q='+encodeURIComponent(query))).status,200);const rows=await f.sudo("select evidence,suggested_action from seo.content_opportunity where kind='keyword_gap' and evidence->>'query'=$1",[query]);assert.equal(rows.length,1);assert.equal(rows[0].evidence.query,query);});
test('PII-like queries are not retained for content opportunities',async()=>{await api('/discovery/search?q=personal%40example.test');const rows=await f.sudo("select query_key from seo.search_query where query_key like '%@%'");assert.equal(rows.length,0);});
test('worker indexing actually populates sources and brand-centered graph',async()=>{const [e]=await f.asRole('pv_app',"select app.emit_event('business.profile_updated','business',$1::text,$1::uuid) id",[business],{'app.user_id':owner.userId,'app.business_id':business});const w=createWorker({client:f.client,env:f.env,logger:silentLogger(),workerId:'discovery-worker'});for(let i=0;i<5;i++)await w.tick(20);const [row]=await f.sudo("select count(*)::int n from seo.entity e join seo.entity_link l on l.to_entity_id=e.id where e.key='business.'||$1::text and e.kind='business'",[business]);assert.equal(row.n,1);const jobs=await f.sudo("select result from ops.job where dedupe_key=$1",['search:'+e.id]);assert.ok(jobs[0].result.indexed_rows>=2);});
test('visibility dashboard states unavailable evidence honestly',async()=>{const r=await api('/admin/discovery');assert.equal(r.status,200);assert.equal(r.json.adapters.gsc.state,'not_configured');assert.equal(r.json.adapters.bing.state,'not_configured');assert.equal(r.json.adapters.ai.state,'not_configured');assert.equal(r.json.observed.length,0);const page=await f.page('/app/search',{host:HOSTS.admin,headers:{cookie}});assert.equal(page.status,200);assert.match(page.body,/provenance/);});
test('manual observation is labelled manual and requires re-auth',async()=>{const value={metric:'mention',value:1,observed_at:new Date().toISOString(),source_url:'https://example.test/evidence',note:'خوداظهاری آزمون، نه provider'};assert.equal((await api('/admin/discovery/observe','POST',value)).status,403);await api('/auth/reauth','POST',{password:admin.password});const r=await api('/admin/discovery/observe','POST',value);assert.equal(r.status,201);assert.equal(r.json.observation.source,'manual');const [o]=await f.sudo('select provenance from seo.visibility_observation where id=$1',[r.json.observation.id]);assert.equal(o.provenance.source,'user_entered_not_provider_verified');});
test('GSC and Bing without credentials never return fake clicks or scores',async()=>{assert.equal((await fetchGsc({startDate:'2026-09-01',endDate:'2026-10-01'})).state,'not_configured');assert.equal((await fetchBing({})).state,'not_configured');const r=await api('/admin/discovery/import','POST',{source:'gsc'});assert.equal(r.status,200);assert.equal(r.json.state,'not_configured');assert.equal(r.json.rows.length,0);});
test('remote provider results are re-authorized from DB, never trusted as data',async()=>{let ids;const adapter=remoteSearchAdapter({driver:'meilisearch',endpoint:'https://search.example.test',key:'test-key',fetch:async()=>({ok:true,json:async()=>({hits:[{id:crypto.randomUUID(),title:'PRIVATE SECRET'}]})}),authorize:async values=>{ids=values;return[];}});const result=await adapter.search({query:'secret',limit:10});assert.ok(ids.length);assert.deepEqual(result,[]);});
test('machine answers cite real public sources and make no synthetic AI visibility claim',async()=>{const r=await api('/geo/answers');assert.equal(r.status,200);assert.equal(r.json.visibility_claims,null);assert.ok(r.json.businesses.some(v=>v.id===business&&v.source.endsWith('/b/discovery-public')));assert.ok(!r.json.businesses.some(v=>v.id===privateBusiness));});
test('business content sitemap includes actual public substantive content',async()=>{const rows=await f.asRole('pv_public','select path,last_modified from seo.sitemap_business_content(100,0)');assert.ok(rows.some(v=>v.path==='/b/discovery-public/c/source-article'));const page=await f.page('/sitemaps/business_content-1.xml');assert.equal(page.status,200);assert.match(page.body,/source-article/);});
