import {test,before,after} from 'node:test';import assert from 'node:assert/strict';import {createFixture,HOSTS} from '../scripts/lib/fixture.mjs';import {totpCode,verifyTotp,newTotpSecret,sealCredential,openCredential,credentialKey} from '../packages/security/dist/index.js';
let f,u,cookie,csrf,secret,challenge,codes;const origin=`http://${HOSTS.panel}`;
async function api(path,method='GET',body){const r=await fetch(f.api.url+'/api/v1/auth'+path,{method,headers:{origin,cookie,'x-csrf-token':csrf,'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});return{status:r.status,json:await r.json(),headers:r.headers};}
before(async()=>{f=await createFixture({api:true});u=await f.registerUser({email:'mfa-real@example.test'});const r=await api('/login','POST',{identifier:u.email,password:u.password});assert.equal(r.status,200);cookie=r.headers.getSetCookie().map(v=>v.split(';')[0]).join('; ');csrf=r.json.csrf_token;assert.equal((await api('/reauth','POST',{password:u.password})).status,200);},{timeout:60000});after(async()=>await f?.close());
test('TOTP RFC-6238 SHA1 dynamic truncation and clock windows',()=>{const s='GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ';assert.equal(totpCode(s,59000),'287082');assert.equal(verifyTotp(s,'287082',59000),1);assert.equal(verifyTotp(s,'000000',59000),null);});
test('credential cipher authenticates contents and never stores plaintext',()=>{const s=newTotpSecret(),key=credentialKey('test-secret'),value=sealCredential(s,key);assert.ok(!value.includes(s));assert.equal(openCredential(value,key),s);assert.throws(()=>openCredential(value.slice(0,-2)+'AA',key));});
test('MFA setup requires fresh password auth and returns secret once via own challenge',async()=>{const r=await api('/mfa/setup','POST',{});assert.equal(r.status,200,JSON.stringify(r.json));secret=r.json.secret;challenge=r.json.challenge.id;assert.match(r.json.uri,/otpauth:\/\/totp\/PETAVU/);const [stored]=await f.sudo('select material from auth.challenge where id=$1',[challenge]);assert.ok(!JSON.stringify(stored).includes(secret));});
test('bad TOTP does not enroll, valid proof enrolls atomically',async()=>{assert.equal((await api('/mfa/confirm','POST',{challenge_id:challenge,code:'000000'})).status,401);const r=await api('/mfa/confirm','POST',{challenge_id:challenge,code:totpCode(secret)});assert.equal(r.status,200,JSON.stringify(r.json));assert.equal(r.json.enabled,true);const [stored]=await f.sudo("select secret_hash from auth.credential where user_id=$1 and kind='totp' and revoked_at is null",[u.userId]);assert.match(stored.secret_hash,/^enc:v1:/);assert.ok(!stored.secret_hash.includes(secret));});
test('enrollment challenge is one-use',async()=>assert.equal((await api('/mfa/confirm','POST',{challenge_id:challenge,code:totpCode(secret)})).status,412));
test('password-only re-auth cannot bypass enrolled second factor',async()=>assert.equal((await api('/reauth','POST',{password:u.password})).status,401));
test('TOTP replay is denied, future-window code works once for re-auth',async()=>{assert.equal((await api('/reauth','POST',{password:u.password,totp:totpCode(secret)})).status,401);const code=totpCode(secret,Date.now()+30000);assert.equal((await api('/reauth','POST',{password:u.password,totp:code})).status,200);assert.equal((await api('/reauth','POST',{password:u.password,totp:code})).status,401);});
test('recovery codes are hashed, one-time and not plaintext in DB',async()=>{const r=await api('/mfa/recovery','POST',{});assert.equal(r.status,200);codes=r.json.codes;assert.equal(codes.length,10);const data=await f.sudo('select code_hash from auth.recovery_code where user_id=$1',[u.userId]);assert.equal(data.length,10);assert.ok(!JSON.stringify(data).includes(codes[0]));assert.equal((await api('/reauth','POST',{password:u.password,recovery_code:codes[0]})).status,200);assert.equal((await api('/reauth','POST',{password:u.password,recovery_code:codes[0]})).status,401);});
test('enrolled account cannot issue password-only login session',async()=>{const r=await api('/login','POST',{identifier:u.email,password:u.password});assert.equal(r.status,401);assert.equal(r.headers.getSetCookie().length,0);});
test('recovery+password login issues a real AAL2 session without storing browser tokens',async()=>{const r=await api('/login','POST',{identifier:u.email,password:u.password,recovery_code:codes[1]});assert.equal(r.status,200,JSON.stringify(r.json));const [s]=await f.sudo('select aal from auth.session where id=$1',[r.json.session.id]);assert.equal(s.aal,2);assert.ok(!r.headers.getSetCookie().join(';').includes('Domain='));});
test('WebAuthn endpoints generate origin-bound one-use challenges and reject fabricated responses',async()=>{const r=await api('/passkeys/options','POST',{});assert.equal(r.status,200,JSON.stringify(r.json));assert.equal(r.json.options.rp.id,'panel.localhost');const bad=await api('/passkeys/register','POST',{challenge_id:r.json.challenge_id,response:{id:'invalid',rawId:'invalid',type:'public-key',response:{clientDataJSON:'bad',attestationObject:'bad'}}});assert.notEqual(bad.status,200);});
test('ordinary DB role cannot read MFA secrets/challenges',async()=>{await assert.rejects(()=>f.asRole('pv_app','select secret_hash from auth.credential'),{code:'42501'});await assert.rejects(()=>f.asRole('pv_public','select material from auth.challenge'),{code:'42501'});});
test('audited impersonation is time-bounded, credential-blocked and visibly marked',async()=>{await f.sudo("update auth.app_user set status='active' where id=$1",[u.userId]);const admin=await f.registerUser({email:'impersonator@example.test'});await f.sudo("insert into auth.user_platform_role(user_id,role_key) values($1,'superadmin')",[admin.userId]);const login=await api('/login','POST',{identifier:admin.email,password:admin.password});const oldCookie=cookie,oldCsrf=csrf;cookie=login.headers.getSetCookie().map(v=>v.split(';')[0]).join('; ');csrf=login.json.csrf_token;try{assert.equal((await api('/impersonation/start','POST',{user_id:u.userId,reason:'بررسی مستند پشتیبانی'})).status,403);assert.equal((await api('/reauth','POST',{password:admin.password})).status,200);const who=(await api('/session')).json;assert.equal(who.session.platform_role,'superadmin');const [permissions]=await f.asRole('pv_app',"select app.has_platform_permission('platform.impersonate') yes",[],{'app.user_id':admin.userId,'app.platform_role':'superadmin','app.session_id':who.session.id});assert.equal(permissions.yes,true);const start=await api('/impersonation/start','POST',{user_id:u.userId,reason:'بررسی مستند پشتیبانی'});assert.equal(start.status,200,JSON.stringify(start.json));cookie=start.headers.getSetCookie().map(v=>v.split(';')[0]).join('; ');csrf=start.json.csrf_token;const [session]=await f.sudo('select impersonated_by,expires_at,created_at from auth.session where id=$1',[start.json.started.session_id]);assert.equal(session.impersonated_by,admin.userId);assert.ok(new Date(session.expires_at)-new Date(session.created_at)<=901000);assert.equal((await api('/mfa/setup','POST',{})).status,403);const page=await f.page('/app/account',{host:HOSTS.panel,headers:{cookie}});assert.equal(page.status,200);assert.match(page.body,/ورود با اختیار کاربر فعال/);const stop=await api('/impersonation/stop','POST',{});assert.equal(stop.status,200);assert.equal(stop.json.relogin_required,true);assert.equal((await api('/session')).status,401);}finally{cookie=oldCookie;csrf=oldCsrf;}});
