import {test,before,after} from 'node:test';import assert from 'node:assert/strict';import {createFixture,HOSTS} from '../scripts/lib/fixture.mjs';
let f,seller,buyer,other,sellBiz,buyBiz,otherBiz,product,order,cartId,cartVersion;
async function login(user,surface){const origin=`http://${HOSTS[surface]}`,r=await fetch(f.api.url+'/api/v1/auth/login',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify({identifier:user.email,password:user.password})});const j=await r.json();assert.equal(r.status,200);return{...user,origin,cookie:r.headers.getSetCookie().map(v=>v.split(';')[0]).join('; '),csrf:j.csrf_token};}
async function api(user,path,method='GET',body,extra={}){const r=await fetch(f.api.url+'/api/v1'+path,{method,headers:{origin:user.origin,cookie:user.cookie,'x-csrf-token':user.csrf,'content-type':'application/json',...extra},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:r.status,json:await r.json()};}
async function fresh(u){assert.equal((await api(u,'/auth/reauth','POST',{password:u.password})).status,200);}
before(async()=>{f=await createFixture({api:true});seller=await login(await f.registerUser({email:'shop-seller@example.test'}),'adminShop');buyer=await login(await f.registerUser({email:'shop-buyer@example.test'}),'shop');other=await login(await f.registerUser({email:'shop-other@example.test'}),'shop');sellBiz=await f.createBusiness({slug:'shop-seller',name:'فروشنده',ownerUserId:seller.userId});buyBiz=await f.createBusiness({slug:'shop-buyer',name:'خریدار',ownerUserId:buyer.userId});otherBiz=await f.createBusiness({slug:'shop-other',name:'دیگری',ownerUserId:other.userId});for(const[u,b]of [[seller,sellBiz],[buyer,buyBiz],[other,otherBiz]]){await f.addMember({businessId:b,userId:u.userId,roleKey:'owner'});assert.equal((await api(u,'/auth/business','POST',{business_id:b})).status,200);}}, {timeout:60000});after(async()=>await f?.close());
test('shop is not the public home or a fake catalog',async()=>{const p=await f.page('/',{host:HOSTS.shop});assert.equal(p.status,200);assert.match(p.body,/فروشگاه B2B/);assert.match(p.body,/هنوز محصول عمومی ثبت نشده/);assert.ok(!p.body.includes('hero__eyebrow'));});
test('both independent private surfaces use API-backed menus and their host-only session',async()=>{for(const[u,host,path]of [[buyer,HOSTS.shop,'/app'],[seller,HOSTS.adminShop,'/app/products']]){const p=await f.page(path,{host,headers:{cookie:u.cookie}});assert.equal(p.status,200,p.body.slice(-600));assert.match(p.headers['cache-control'],/no-store/);assert.match(p.body,/panel-body--(?:shop|admin_shop)/);}const m=await api(buyer,'/panel/menu?surface=shop');assert.equal(m.json.items.length,4);const a=await api(seller,'/panel/menu?surface=admin_shop');assert.equal(a.json.items.length,5);});
test('create product starts Draft with zero real stock, never pretends available',async()=>{const r=await api(seller,'/shop/manage/products','POST',{sku:'REAL-1',title:'محصول واقعی آزمایش',description:'فقط دادهٔ آزمون مستقل',price_minor:'1250',currency:'EUR'});assert.equal(r.status,201,JSON.stringify(r.json));product=r.json.product;assert.equal(product.stock_qty,0);assert.equal(product.status,'draft');assert.equal((await api(buyer,'/shop/products/'+product.id)).status,404);});
test('publish and inventory edits require fresh auth and safe server versions',async()=>{assert.equal((await api(seller,'/shop/manage/products/'+product.id+'/stock','POST',{expected_version:product.version,quantity:4,reason:'تحویل واقعی'})).status,403);await fresh(seller);let r=await api(seller,'/shop/manage/products/'+product.id+'/stock','POST',{expected_version:product.version,quantity:4,reason:'تحویل واقعی'});assert.equal(r.status,200);product=r.json.product;r=await api(seller,'/shop/manage/products/'+product.id+'/state','POST',{expected_version:product.version,to:'published'});assert.equal(r.status,200);product=r.json.product;const page=await f.page('/products/'+product.id,{host:HOSTS.shop});assert.equal(page.status,200);assert.match(page.body,/1250 EUR/);});
test('foreign product management and context forgery are denied',async()=>{assert.equal((await api(buyer,'/shop/manage/products/'+product.id,'PUT',{expected_version:product.version,title:'ربودن',price_minor:'1'})).status,403);assert.equal((await api(buyer,'/shop/cart','GET',undefined,{'x-business-id':sellBiz})).status,403);const raw=await f.asRole('pv_app','select id from app.shop_order',[],{'app.user_id':other.userId,'app.business_id':otherBiz});assert.equal(raw.length,0);});
test('cart ignores injected prices and cannot spend or reserve stock',async()=>{const r=await api(buyer,'/shop/cart','POST',{product_id:product.id,quantity:2,expected_version:0,price_minor:'1'});assert.equal(r.status,200);cartId=r.json.cart.id;cartVersion=r.json.cart.version;const cart=await api(buyer,'/shop/cart');assert.equal(cart.json.items[0].price_minor,'1250');assert.equal(cart.json.items[0].total_minor,'2500');const [p]=await f.sudo('select reserved_qty from app.shop_product where id=$1',[product.id]);assert.equal(p.reserved_qty,0);});
test('checkout reserves atomically, is idempotent and explicitly does not take payment',async()=>{await fresh(buyer);const key=crypto.randomUUID();const body={cart_id:cartId,expected_version:cartVersion,idempotency_key:key};const r=await api(buyer,'/shop/checkout','POST',body);assert.equal(r.status,201,JSON.stringify(r.json));order=r.json.order;assert.equal(order.total_minor,'2500');assert.equal(order.payment_status,'unconfigured');assert.equal(r.json.payment.state,'not_configured');const again=await api(buyer,'/shop/checkout','POST',body);assert.equal(again.status,201);assert.equal(again.json.order.id,order.id);const [p]=await f.sudo('select reserved_qty,stock_qty from app.shop_product where id=$1',[product.id]);assert.deepEqual(p,{reserved_qty:2,stock_qty:4});assert.equal((await f.sudo('select count(*)::int n from app.stock_movement where order_id=$1',[order.id]))[0].n,1);});
test('reserved units cannot be oversold or adjusted away',async()=>{const p=(await api(seller,'/shop/manage/products')).json.items.find(v=>v.id===product.id);assert.equal((await api(seller,'/shop/manage/products/'+product.id+'/stock','POST',{expected_version:p.version,quantity:1,reason:'خطرناک'})).status,412);await fresh(other);const cart=await api(other,'/shop/cart','POST',{product_id:product.id,quantity:3,expected_version:0});assert.equal(cart.status,200);const r=await api(other,'/shop/checkout','POST',{cart_id:cart.json.cart.id,expected_version:cart.json.cart.version,idempotency_key:crypto.randomUUID()});assert.equal(r.status,412);assert.equal((await f.sudo('select reserved_qty from app.shop_product where id=$1',[product.id]))[0].reserved_qty,2);});
test('only seller confirms/fulfills and ledger consumes exactly once',async()=>{const fake=await api(buyer,'/shop/orders/'+order.id+'/state','POST',{expected_version:order.version,to:'confirmed',reason:'من فروشنده نیستم'});assert.equal(fake.status,412);let r=await api(seller,'/shop/orders/'+order.id+'/state','POST',{expected_version:order.version,to:'confirmed',reason:'تأیید فروشنده'});assert.equal(r.status,200);order=r.json.order;r=await api(seller,'/shop/orders/'+order.id+'/state','POST',{expected_version:order.version,to:'fulfilled',reason:'تحویل واقعی'});assert.equal(r.status,200);const [p]=await f.sudo('select stock_qty,reserved_qty from app.shop_product where id=$1',[product.id]);assert.deepEqual(p,{stock_qty:2,reserved_qty:0});assert.equal((await api(seller,'/shop/orders/'+order.id+'/state','POST',{expected_version:order.version,to:'fulfilled',reason:'تکرار'})).status,409);});
test('raw application stock updates cannot bypass transactional ledger',async()=>{await assert.rejects(()=>f.asRole('pv_app','update app.shop_product set stock_qty=100 where id=$1',[product.id],{'app.user_id':seller.userId,'app.business_id':sellBiz}),{code:'55000'});});
test('product pricing does not accept floating point money or unknown currency',async()=>{for(const value of [{price_minor:'12.50',currency:'EUR'},{price_minor:'1',currency:'BTC'}])assert.equal((await api(seller,'/shop/manage/products','POST',{sku:crypto.randomUUID(),title:'محصول',...value})).status,400);});
test('orders never leak to unrelated buyer',async()=>{const r=await api(other,'/shop/orders');assert.equal(r.status,200);assert.ok(!r.json.items.some(v=>v.id===order.id));});
