import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {createFixture,HOSTS} from '../scripts/lib/fixture.mjs';
import {compilePreview,contrastRatio,publicDesignPath} from '../packages/design/dist/pipeline.js';
let f,owner,other,admin,business,otherBusiness,pageId,first,second,token,originalCss;
const long='این متن برای معرفی خدمت واقعی کسب‌وکار و توضیح اطلاعات قابل انتشار آن نوشته می‌شود؛ این داده فقط در آزمون مستقل ساخته شده و به نصب معمولی نمی‌رود. ';
const tree=(text='عنوان آزمایش واقعی')=>({version:1,root:[{id:'h',component:'content.heading',props:{text,level:'h1'}},{id:'p',component:'content.paragraph',props:{text:long}}]});
async function login(u,surface){const origin=`http://${HOSTS[surface]}`;const r=await fetch(f.api.url+'/api/v1/auth/login',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify({identifier:u.email,password:u.password})});const j=await r.json();assert.equal(r.status,200,JSON.stringify(j));return {...u,origin,cookie:r.headers.getSetCookie().map(v=>v.split(';')[0]).join('; '),csrf:j.csrf_token,sessionId:j.session.id};}
async function call(u,path='',method='GET',body,headers={}){const r=await fetch(f.api.url+'/api/v1'+path,{method,headers:{origin:u.origin,cookie:u.cookie,'x-csrf-token':u.csrf,'content-type':'application/json',...headers},...(body===undefined?{}:{body:JSON.stringify(body)})});return {status:r.status,json:await r.json()};}
const api=(path='',method='GET',body,u=owner,headers={})=>call(u,'/studio'+path,method,body,headers);
const getRelease=async(id,u=owner,suffix='')=>(await api('/releases/'+id+suffix,'GET',undefined,u)).json.release;
async function fresh(u){assert.equal((await call(u,'/auth/reauth','POST',{password:u.password})).status,200);}
async function prepare(u=owner,suffix=''){const r=await api('/releases'+suffix,'POST',{},u);assert.equal(r.status,201,JSON.stringify(r.json));return r.json.id;}
async function fullPublish(id,u=owner,suffix=''){const validated=await api(`/releases/${id}/validate${suffix}`,'POST',{},u);assert.equal(validated.status,200,JSON.stringify(validated.json));assert.equal(validated.json.release.status,'validating',JSON.stringify(validated.json.report.checks.filter(v=>v.status==='failed')));let preview=await api(`/releases/${id}/preview${suffix}`,'POST',{},u);assert.equal(preview.status,200,JSON.stringify(preview.json));await fresh(u);const a=await api(`/releases/${id}/approve${suffix}`,'POST',{expected_version:preview.json.release.lock_version},u);assert.equal(a.status,200,JSON.stringify(a.json));const p=await api(`/releases/${id}/publish${suffix}`,'POST',{expected_version:a.json.release.lock_version},u);assert.equal(p.status,200,JSON.stringify(p.json));return p.json.release;}
before(async()=>{f=await createFixture({api:true});owner=await f.registerUser({email:'studio-owner@example.test'});other=await f.registerUser({email:'studio-other@example.test'});admin=await f.registerUser({email:'studio-admin@example.test'});await f.sudo("insert into auth.user_platform_role(user_id,role_key) values($1,'superadmin')",[admin.userId]);owner=await login(owner,'panel');other=await login(other,'panel');admin=await login(admin,'admin');business=await f.createBusiness({slug:'studio-owner',name:'طراحی واقعی',ownerUserId:owner.userId});otherBusiness=await f.createBusiness({slug:'studio-other',name:'مالک دیگر',ownerUserId:other.userId});await f.addMember({businessId:business,userId:owner.userId,roleKey:'owner'});await f.addMember({businessId:otherBusiness,userId:other.userId,roleKey:'owner'});assert.equal((await call(owner,'/auth/business','POST',{business_id:business})).status,200);assert.equal((await call(other,'/auth/business','POST',{business_id:otherBusiness})).status,200);const created=await api('/pages','POST',{key:'home',title:'طراحی واقعی',tree:tree()});assert.equal(created.status,201,JSON.stringify(created.json));pageId=created.json.page.id;}, {timeout:60000});
after(async()=>await f?.close());
test('member studio and all 15 entries are real handlers',async()=>{const p=await f.page('/app/pages',{host:HOSTS.panel,headers:{cookie:owner.cookie}});assert.equal(p.status,200);assert.match(p.body,/استودیو|صفحه‌ها و طراحی/);assert.match(p.body,/name="component"/);assert.match(p.body,/studio-tree/);assert.match(p.headers['cache-control'],/no-store/);});
test('staff studio and tokens are API-backed separate admin pages',async()=>{for(const path of ['/app/design','/app/tokens']){const p=await f.page(path,{host:HOSTS.admin,headers:{cookie:admin.cookie}});assert.equal(p.status,200);assert.match(p.body,/panel-body--admin/);}});
test('ordinary identity denied explicit platform scope',async()=>assert.equal((await api('?scope=platform')).status,403));
test('unknown scope is invalid rather than broadened',async()=>assert.equal((await api('?scope=all')).status,400));
test('business scope derives from active session, not forged header',async()=>assert.equal((await api('','GET',undefined,owner,{'x-business-id':otherBusiness})).status,403));
test('page IDOR is hidden even for valid UUID',async()=>assert.equal((await api('/pages/'+pageId,'GET',undefined,other)).status,404));
test('node builder cannot create arbitrary component',async()=>{const p=(await api('/pages/'+pageId)).json.page;assert.equal((await api('/pages/'+pageId+'/nodes','POST',{expected_version:p.version,component:'danger.sql',props:{sql:'drop table'}})).status,400);});
test('invalid nested props/JS and duplicate identities are rejected',async()=>{const p=(await api('/pages/'+pageId)).json.page;for(const invalid of [{version:1,root:[{id:'s',component:'layout.section',slots:{children:[{id:'nested',component:'content.heading',props:{text:'bad',style:'color:red',level:'h1'}}]}}]}, {version:1,root:[{id:'same',component:'content.heading',props:{text:'x',level:'h1'}},{id:'same',component:'content.paragraph',props:{text:'x'}}]}, {version:3,root:[]}]){const r=await api('/pages/'+pageId,'PUT',{expected_version:p.version,tree:invalid});assert.equal(r.status,400,JSON.stringify(r.json));}});
test('stale version cannot overwrite a saved draft',async()=>{const p=(await api('/pages/'+pageId)).json.page;const a=await api('/pages/'+pageId,'PUT',{expected_version:p.version,tree:tree('نخستین تغییر')});assert.equal(a.status,200);const stale=await api('/pages/'+pageId,'PUT',{expected_version:p.version,tree:tree('از دست رفته')});assert.equal(stale.status,409);});
test('draft is not public before a release',async()=>{const p=await f.page('/b/studio-owner');assert.equal(p.status,200);assert.ok(!p.body.includes('نخستین تغییر'));});
test('raw live page insertion/update/delete is blocked at DB as well as API',async()=>{const ctx={'app.user_id':owner.userId,'app.business_id':business};await assert.rejects(()=>f.asRole('pv_app',"insert into design.page(business_id,key,title,status,published_tree) values($1,'bypass','دور زدن','published','{}')",[business],ctx),{code:'55000'});await assert.rejects(()=>f.asRole('pv_app',"update design.page set published_tree=draft_tree,status='published' where id=$1",[pageId],ctx),{code:'55000'});await assert.rejects(()=>f.asRole('pv_app','delete from design.page where id=$1',[pageId],ctx),{code:'55000'});assert.equal((await call(owner,`/businesses/${business}/pages/home/publish`,'POST',{})).status,412);});
test('tokens remain inherited live until override is approved/published',async()=>{const initial=(await api()).json;const global=initial.tokens.find(v=>v.key==='color.brand.600'&&v.theme_mode==='light');assert.ok(global);const t=await api('/tokens/'+global.id+'/override','POST',{});assert.equal(t.status,201);token=t.json.token;const saved=await api('/tokens/'+token.id,'PUT',{expected_version:token.version,value:'#2D617E'});assert.equal(saved.status,200);token=saved.json.token;const rows=await f.asRole('pv_public','select key,value from design.public_tokens($1)',[business]);assert.notEqual(rows.find(v=>v.key==='color.brand.600').value,'#2D617E');});
test('release snapshots SHA-256 and prepare is effect-idempotent for unchanged pending source',async()=>{first=await prepare();const again=await prepare();assert.equal(again,first);const r=await getRelease(first);assert.match(r.bundle_hash,/^sha256:[0-9a-f]{64}$/);assert.equal(r.version,1);assert.ok(r.bundle.registry.length>=40);});
test('immutable deployment version and bundle cannot be mutated directly',async()=>{await assert.rejects(()=>f.sudo('update design.release set bundle=$1::jsonb where id=$2',[JSON.stringify({pages:[]}),first]),{code:'55000'});});
test('approval requires real validation/preview and fresh auth',async()=>{let r=await getRelease(first);const a=await api('/releases/'+first+'/approve','POST',{expected_version:r.lock_version});assert.equal(a.status,403);await fresh(owner);r=await getRelease(first);assert.equal((await api('/releases/'+first+'/approve','POST',{expected_version:r.lock_version})).status,412);});
test('actual generated HTML, CSS, fonts and resource budgets produce evidence; CWV are not invented',async()=>{const v=await api('/releases/'+first+'/validate','POST',{});assert.equal(v.status,200);assert.equal(v.json.release.status,'validating',JSON.stringify(v.json.report.checks.filter(v=>v.status==='failed')));const evidence=v.json.report.checks.find(v=>v.stage==='PERFORMANCE').evidence;assert.ok(evidence.delivery[0].measurement.font_kb>70);assert.ok(evidence.delivery[0].measurement.css_kb>0);assert.ok(evidence.delivery[0].measurement.html_kb>0);assert.ok(evidence.delivery[0].budget.not_compared.includes('lcp_ms'));assert.equal(evidence.cwv,'not_compared_without_browser_samples');const r=await getRelease(first);assert.equal((await api('/releases/'+first+'/approve','POST',{expected_version:r.lock_version})).status,412);});
test('preview renders immutable source and records the actor/hash, not just a link',async()=>{const p=await api('/releases/'+first+'/preview','POST',{});assert.equal(p.status,200);assert.match(p.json.preview.html,/نخستین تغییر/);assert.match(p.json.preview.document,/noindex/);assert.equal(p.json.release.previewed_hash,p.json.release.bundle_hash);assert.ok(p.json.release.previewed_at);});
test('approved snapshot publishes atomically with tokens, audit and outbox',async()=>{const r=await getRelease(first);const a=await api('/releases/'+first+'/approve','POST',{expected_version:r.lock_version});assert.equal(a.status,200,JSON.stringify(a.json));const p=await api('/releases/'+first+'/publish','POST',{expected_version:a.json.release.lock_version});assert.equal(p.status,200,JSON.stringify(p.json));assert.equal(p.json.release.status,'published');assert.equal(p.json.release.version,1);assert.ok(p.json.release.lock_version>1);const live=await f.page('/b/studio-owner');assert.match(live.body,/نخستین تغییر/);originalCss=/<link rel="stylesheet" href="([^"]+)"/.exec(live.body)?.[1];assert.ok(originalCss);const css=await f.page(originalCss);assert.match(css.bytes.toString(),/#2D617E/);const [audit]=await f.sudo("select count(*)::int n from ops.audit_log where action='design.published'");assert.ok(audit.n>=1);const [event]=await f.sudo("select count(*)::int n from ops.event where event_type='design.published'");assert.ok(event.n>=1);});
test('draft edit cannot change public CSS or published HTML',async()=>{const p=(await api('/pages/'+pageId)).json.page;await api('/pages/'+pageId,'PUT',{expected_version:p.version,tree:tree('نسخهٔ دوم')});const t=(await api()).json.tokens.find(v=>v.id===token.id);await api('/tokens/'+token.id,'PUT',{expected_version:t.version,value:'#395D36'});const live=await f.page('/b/studio-owner');assert.match(live.body,/نخستین تغییر/);assert.ok(!live.body.includes('نسخهٔ دوم'));assert.equal(/<link rel="stylesheet" href="([^"]+)"/.exec(live.body)?.[1],originalCss);});
test('source drift invalidates approval even after validation and preview',async()=>{const id=await prepare();await api('/releases/'+id+'/validate','POST',{});const preview=await api('/releases/'+id+'/preview','POST',{});const p=(await api('/pages/'+pageId)).json.page;await api('/pages/'+pageId,'PUT',{expected_version:p.version,tree:tree('نسخهٔ سوم')});assert.equal((await api('/releases/'+id+'/approve','POST',{expected_version:preview.json.release.lock_version})).status,412);});
test('builder routes publish custom pages with real routing and sitemap coverage',async()=>{const created=await api('/pages','POST',{key:'service_page',title:'صفحهٔ خدمت واقعی',tree:tree('خدمت واقعی')});assert.equal(created.status,201);const id=await prepare();second=await fullPublish(id);const page=await f.page('/b/studio-owner/service_page');assert.equal(page.status,200,page.body.slice(-400));assert.match(page.body,/خدمت واقعی/);const entries=await f.asRole('pv_public','select path,last_modified from design.sitemap_pages(100,0)');assert.ok(entries.some(v=>v.path==='/b/studio-owner/service_page'));assert.equal((await f.page('/sitemaps/design-1.xml')).status,200);});
test('rollback restores exact previous pages/tokens/SEO, but preserves later drafts',async()=>{const r=await getRelease(first);const rollback=await api('/releases/'+first+'/rollback','POST',{expected_version:r.lock_version});assert.equal(rollback.status,200,JSON.stringify(rollback.json));assert.equal(rollback.json.release.bundle_hash,r.bundle_hash);const live=await f.page('/b/studio-owner');assert.match(live.body,/نخستین تغییر/);assert.ok(!live.body.includes('نسخهٔ سوم'));assert.equal(/<link rel="stylesheet" href="([^"]+)"/.exec(live.body)?.[1],originalCss);const draft=(await api('/pages/'+pageId)).json.page;assert.equal(draft.draft_tree.root[0].props.text,'نسخهٔ سوم');assert.equal((await f.page('/b/studio-owner/service_page')).status,404);const [old]=await f.sudo('select status,is_current from design.release where id=$1',[second.id]);assert.equal(old.status,'rolled_back');assert.equal(old.is_current,false);});
test('rollback to the same current release is effect-idempotent',async()=>{const r=await getRelease(first);const a=await api('/releases/'+first+'/rollback','POST',{expected_version:r.lock_version});assert.equal(a.status,200);assert.equal(a.json.release.lock_version,r.lock_version);});
test('tenant cannot read another release, revision or diff bundle',async()=>{assert.equal((await api('/releases/'+first,'GET',undefined,other)).status,404);assert.equal((await api('/pages/'+pageId+'/revisions','GET',undefined,other)).status,404);assert.equal((await api(`/compare?from=${first}&to=${second.id}`,'GET',undefined,other)).status,404);});
test('stale release lock cannot publish or rollback',async()=>assert.equal((await api('/releases/'+first+'/rollback','POST',{expected_version:1})).status,409));
test('unauthorized global draft columns are invisible through API and RLS',async()=>{const overview=(await api('?scope=platform','GET',undefined,admin)).json;const t=overview.tokens.find(v=>v.key==='color.brand.600'&&v.theme_mode==='light');const drafted=await api('/tokens/'+t.id+'?scope=platform','PUT',{expected_version:t.version,value:'#214A74'},admin);assert.equal(drafted.status,200);const member=(await api()).json.tokens.find(v=>v.id===t.id);assert.equal(member.draft_value,null);assert.equal(member.has_draft,false);const raw=await f.asRole('pv_app','select id from design.token where id=$1',[t.id],{'app.user_id':owner.userId,'app.business_id':business});assert.equal(raw.length,0);});
test('contrast validator uses WCAG sRGB math, not a hardcoded pass',()=>{assert.equal(contrastRatio('#000000','#ffffff'),21);assert.equal(contrastRatio('#ffffff','#ffffff'),1);assert.equal(contrastRatio('garbage','#ffffff'),null);assert.equal(publicDesignPath('home','اصفهان'),'/b/'+encodeURIComponent('اصفهان'));});
void compilePreview;
test('theme setting edit is staged; schema forbids arbitrary code and resolves typed aliases',async()=>{const o=(await api('?scope=platform','GET',undefined,admin)).json;const t=o.themes[0];const bad=await api('/themes/'+t.id+'?scope=platform','PUT',{expected_version:t.version,settings:{sql:'select secrets'}},admin);assert.equal(bad.status,400);const settings={...t.settings,radius_base_token:'radius.sm'};const good=await api('/themes/'+t.id+'?scope=platform','PUT',{expected_version:t.version,settings},admin);assert.equal(good.status,200);const [live]=await f.asRole('pv_public','select design.public_theme_settings(null) settings');assert.notEqual(live.settings.radius_base_token,'radius.sm');});
test('platform publication invalidates live CSS cache, but preceding draft did not',async()=>{const initial=await f.page('/');const before=/<link rel="stylesheet" href="([^"]+)"/.exec(initial.body)?.[1];const created=await api('/pages?scope=platform','POST',{key:'home',title:'پتاوو برای صنعت',tree:tree('استودیوی سراسری')},admin);assert.equal(created.status,201);const still=await f.page('/');assert.equal(/<link rel="stylesheet" href="([^"]+)"/.exec(still.body)?.[1],before);const id=await prepare(admin,'?scope=platform');await fullPublish(id,admin,'?scope=platform');const after=await f.page('/');assert.match(after.body,/استودیوی سراسری/);const changed=/<link rel="stylesheet" href="([^"]+)"/.exec(after.body)?.[1];assert.notEqual(changed,before);assert.match((await f.page(changed)).bytes.toString(),/#214A74/);});
test('actual budget breach cannot be forged green by a report in the request',async()=>{const [old]=await f.sudo("select weight_kb from ops.page_budget where route_pattern='/b/:slug' and scope='platform'");await f.sudo("update ops.page_budget set weight_kb=10 where route_pattern='/b/:slug' and scope='platform'");try{const id=await prepare();const validated=await api('/releases/'+id+'/validate','POST',{report:{checks:[{stage:'PERFORMANCE',status:'passed'}]}});assert.equal(validated.status,200);assert.equal(validated.json.release.status,'failed');const evidence=validated.json.report.checks.find(v=>v.stage==='PERFORMANCE');assert.equal(evidence.status,'failed');assert.ok(evidence.evidence.delivery.some(v=>v.budget.breaches.some(b=>b.metric==='weight_kb')));assert.equal((await api('/releases/'+id+'/approve','POST',{expected_version:validated.json.release.lock_version})).status,412);}finally{await f.sudo("update ops.page_budget set weight_kb=$1 where route_pattern='/b/:slug' and scope='platform'",[old.weight_kb]);}});
test('raw malformed root fields and unsafe slot names are refused without mutation',async()=>{const p=(await api('/pages/'+pageId)).json.page;assert.equal((await api('/pages/'+pageId,'PUT',{expected_version:p.version,tree:{...tree(),script:'evil()'}})).status,400);assert.equal((await api('/pages/'+pageId+'/nodes','POST',{expected_version:p.version,component:'content.paragraph',parent_id:'h',slot:'__proto__',props:{text:'x'}})).status,400);const actual=(await api('/pages/'+pageId)).json.page;assert.equal(actual.version,p.version);});
test('BFF Preview isolates public CSS and semantics inside a script-disabled same-origin frame',async()=>{const r=await f.web.render({url:'/app/pages/preview',host:HOSTS.panel,method:'POST',body:new URLSearchParams({_csrf:owner.csrf,id:first,expected_version:String((await getRelease(first)).lock_version)}).toString(),headers:{cookie:owner.cookie,origin:owner.origin,'content-type':'application/x-www-form-urlencoded'}});assert.equal(r.status,200,r.body.slice(-500));assert.match(r.body,/<iframe[^>]+sandbox="allow-same-origin"/);assert.match(r.body,/srcdoc=/);assert.match(r.body,/studio-preview\.[0-9a-f]+\.css/);assert.ok(!r.body.includes('allow-scripts'));assert.equal((r.body.match(/<h1\b/g)||[]).length,1);assert.match(r.headers['cache-control'],/no-store/);});
