import {randomBytes,createHmac,createHash,createCipheriv,createDecipheriv,timingSafeEqual} from 'node:crypto';
const ALPHABET='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
export function base32(bytes:Buffer):string{let bits=0,value=0,result='';for(const b of bytes){value=(value<<8)|b;bits+=8;while(bits>=5){result+=ALPHABET[(value>>>(bits-5))&31];bits-=5;}}if(bits)result+=ALPHABET[(value<<(5-bits))&31];return result;}
export function unbase32(value:string):Buffer{let bits=0,number=0;const out:number[]=[];for(const c of value.toUpperCase().replace(/=+$/,'')){const index=ALPHABET.indexOf(c);if(index<0)throw new Error('invalid_base32');number=(number<<5)|index;bits+=5;if(bits>=8){out.push((number>>>(bits-8))&255);bits-=8;}}return Buffer.from(out);}
export function newTotpSecret():string{return base32(randomBytes(20));}
export function totpCode(secret:string,nowMs=Date.now()):string{const counter=Math.floor(nowMs/30000),buffer=Buffer.alloc(8);buffer.writeBigUInt64BE(BigInt(counter));const hash=createHmac('sha1',unbase32(secret)).update(buffer).digest();const offset=hash[hash.length-1]!&15;const value=(hash.readUInt32BE(offset)&0x7fffffff)%1000000;return value.toString().padStart(6,'0');}
export function verifyTotp(secret:string,code:string,nowMs=Date.now()):number|null{if(!/^\d{6}$/.test(code))return null;for(const delta of [-1,0,1]){const time=nowMs+delta*30000,expected=totpCode(secret,time);if(timingSafeEqual(Buffer.from(expected),Buffer.from(code)))return Math.floor(time/30000);}return null;}
export function credentialKey(sessionSecret:string,production=false):Buffer{const raw=process.env['CREDENTIAL_ENCRYPTION_KEY'];if(raw){const key=Buffer.from(raw,'base64');if(key.length!==32)throw new Error('credential_key_requires_32_bytes');return key;}if(production)throw new Error('CREDENTIAL_ENCRYPTION_KEY required');return createHash('sha256').update('petavu-development-credential-key:'+sessionSecret).digest();}
export function sealCredential(secret:string,key:Buffer):string{const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',key,iv);cipher.setAAD(Buffer.from('petavu:mfa:v1'));const body=Buffer.concat([cipher.update(secret,'utf8'),cipher.final()]);return['enc','v1',iv.toString('base64url'),cipher.getAuthTag().toString('base64url'),body.toString('base64url')].join(':');}
export function openCredential(value:string,key:Buffer):string{const parts=value.split(':');if(parts.length!==5||parts[0]!=='enc'||parts[1]!=='v1')throw new Error('invalid_cipher');const decipher=createDecipheriv('aes-256-gcm',key,Buffer.from(parts[2]!,'base64url'));decipher.setAAD(Buffer.from('petavu:mfa:v1'));decipher.setAuthTag(Buffer.from(parts[3]!,'base64url'));return Buffer.concat([decipher.update(Buffer.from(parts[4]!,'base64url')),decipher.final()]).toString('utf8');}
export * from '@simplewebauthn/server';
