import {escapeText,tag,raw} from '../html.js';
import {describeProblem} from './core.js';
import {card,pageHeader,formBlock,emptyNote,dataTable,actionForm,htmlOf,type Field} from './kit.js';
import type {Section,PanelCtx,ActionOutcome} from './types.js';
type Json=Record<string,unknown>;
const str=(v:unknown)=>v==null?'':String(v),json=(v:unknown)=>JSON.stringify(v,null,2);
const values=(j:Json|null,k:string)=>Array.isArray(j?.[k])?j[k] as Json[]:[];
const base=(c:PanelCtx,p='')=>'/api/v1/nocode'+p+(c.surface==='admin'?(p.includes('?')?'&':'?')+'scope=platform':'');
const hidden=(name:string,value:unknown):Field=>({name,label:name,type:'hidden',value:str(value)});
export function nocodeSection(key='nocode'):Section{const path='/app/'+key;const send=async(c:PanelCtx,method:'POST'|'PUT'|'DELETE',suffix:string,body:unknown):Promise<ActionOutcome>=>{const r=await c.api(method,base(c,suffix),body);return{redirect:path+(key==='pages'?'?builder=nocode':''),flash:{kind:r.status<300?'success':'error',text:r.status<300?'داده در سرور ثبت شد.':describeProblem(r)}};};
 const parse=(c:PanelCtx,name:string)=>JSON.parse(c.form?.[name]??'{}') as Json;
 const guarded=async(fn:()=>Promise<ActionOutcome>,p:string):Promise<ActionOutcome>=>{try{return await fn();}catch{return{redirect:p,flash:{kind:'error',text:'JSON خوانا نیست یا API در دسترس نبود.'}};}};
 return{key,title:'سازنده‌های No-Code',async render(c){const r=await c.api('GET',base(c));if(r.status!==200)return{status:r.status,html:htmlOf(pageHeader('سازنده‌های No-Code'),emptyNote(describeProblem(r)))};const defs=values(r.json,'definitions');const kinds=Array.from(new Set(defs.map(d=>str(d['kind']))));const create=card('Standard Mode — فیلد',formBlock({id:'nc-field',action:path+'/nc-field',csrf:c.csrf,fields:[{name:'key',label:'کلید',required:true,dir:'ltr',maxLength:60},{name:'label',label:'برچسب',required:true,maxLength:200},{name:'type',label:'نوع',type:'select',options:values(r.json,'types').filter(v=>!['enum','reference'].includes(str(v))).map(v=>({value:str(v),label:str(v)}))},{name:'public',label:'مجاز در خروجی عمومی',type:'select',options:[{value:'false',label:'خیر — پیش‌فرض خصوصی'},{value:'true',label:'بله'}]},{name:'required',label:'اجباری',type:'select',options:[{value:'false',label:'خیر'},{value:'true',label:'بله'}]}],submit:'ساخت فیلد Draft'}));
 const advanced=card('Advanced Mode — همان DSL محدود',formBlock({id:'nc-definition',action:path+'/nc-create',csrf:c.csrf,fields:[{name:'key',label:'کلید تعریف',required:true,maxLength:60,dir:'ltr'},{name:'kind',label:'نوع Builder',type:'select',options:['field','relationship','form','crud'].map(v=>({value:v,label:v}))},{name:'spec',label:'تعریف داده‌ای JSON',type:'textarea',dir:'ltr',rows:10,maxLength:18000,value:'{}',hint:'Form/CRUD با field_ids به فیلدها اشاره می‌کنند. هیچ SQL/HTML/JS پذیرفته نمی‌شود. انتشار از استودیو و صفحهٔ واقعی انجام می‌شود.'}],submit:'ساخت Draft و Page/CRUD'}));
 const list=card('تعریف‌ها — Draft جدا از live',kinds.map(kind=>tag('details',{},tag('summary',{},escapeText(kind))+defs.filter(d=>d['kind']===kind).map(d=>tag('details',{},tag('summary',{},escapeText(str(d['key'])+' · '+str(d['id'])))+tag('pre',{class:'studio-code',dir:'ltr'},escapeText(json(d['spec'])))+actionForm({action:path+'/nc-revisions',csrf:c.csrf,label:'نسخه‌ها و مقایسه / بازگردانی Draft',hidden:{id:str(d['id']),expected_version:str(d['version'])}}).__html+(c.surface==='admin'||d['business_id']!==null?formBlock({id:'nc-'+str(d['id']),action:path+'/nc-save',csrf:c.csrf,fields:[hidden('id',d['id']),hidden('expected_version',d['version']),{name:'spec',label:'پیش‌نویس تعریف',type:'textarea',dir:'ltr',value:json(d['spec']),rows:8,maxLength:18000}],submit:'ذخیرهٔ Draft'}):emptyNote('کتابخانهٔ مشترک، فقط نسخهٔ منتشرشده است.')))).join(''))).join(''));
 const model=defs.find(d=>d['id']===c.url.searchParams.get('model')&&d['kind']==='crud')??defs.find(d=>d['kind']==='crud'&&d['live_enabled']===true&&(c.surface==='admin'||d['business_id']!==null));let records='';if(model){const rr=await c.api('GET',base(c,'/records?definition_id='+str(model['id'])).replace('?definition_id='+str(model['id'])+'?scope=platform','?definition_id='+str(model['id'])+'&scope=platform'));records=card('CRUD واقعی روی content',htmlOf(formBlock({id:'nc-record-create',action:path+'/nc-record-create',csrf:c.csrf,fields:[hidden('definition_id',model['id']),{name:'slug',label:'نامک رکورد',required:true,maxLength:120},{name:'values',label:'مقادیر فیلدها (JSON)',type:'textarea',dir:'ltr',value:'{}',rows:6,maxLength:18000}],submit:'ساخت پیش‌نویس content'}),dataTable({caption:'رکوردها',columns:[{key:'title',label:'عنوان'},{key:'status',label:'وضعیت'},{key:'version',label:'نسخه'}],rows:values(rr.json,'items').map(v=>({title:raw(tag('a',{href:path+'?builder=nocode&record='+str(v['id'])},escapeText(str(v['title'])))),status:str(v['status']),version:str(v['version'])})),empty:'این مدل هنوز رکورد ندارد.'})));}
 const selected=c.url.searchParams.get('record');if(selected){const edit=await c.api('GET',base(c,'/records/'+encodeURIComponent(selected)));const row=edit.json?.['record'] as Json|undefined;if(row)records+=card('ویرایش رکورد '+str(row['title']),htmlOf(formBlock({id:'nc-record-edit',action:path+'/nc-record-save',csrf:c.csrf,fields:[hidden('id',row['id']),hidden('expected_version',row['version']),{name:'values',label:'مقادیر مجاز',type:'textarea',dir:'ltr',rows:10,value:json(row['values']),maxLength:18000}],submit:'ذخیرهٔ اتمی'}),actionForm({action:path+'/nc-record-delete',csrf:c.csrf,label:'حذف نرم',hidden:{id:str(row['id']),expected_version:str(row['version'])},tone:'danger'})));}
 const submissions=await c.api('GET',base(c,'/submissions'));const inbox=card('درخواست‌های ذخیره‌شده',dataTable({caption:'فرم‌ها',columns:[{key:'id',label:'رسید'},{key:'form',label:'فرم'},{key:'values',label:'دادهٔ خصوصی'},{key:'consent',label:'رضایت'}],rows:values(submissions.json,'items').map(v=>({id:str(v['id']),form:str(v['form_id']),values:json(v['values']),consent:v['consented']?'بله':'خیر'})),empty:submissions.status===200?'درخواستی ثبت نشده است.':'دیدن درخواست‌ها مجوز content.review می‌خواهد.'}));
 return{html:htmlOf(pageHeader('Field / Relationship / Form / Page-CRUD',{subtitle:'امنیت و workflow اصلی حفظ می‌شوند. فرم داده را ثبت می‌کند؛ ارسال اعلان تابع Worker و پیکربندی واقعی است.'}),tag('a',{class:'button button--ghost',href:c.surface==='admin'?'/app/design':'/app/pages'},'رفتن به Preview / Approval / Publish'),create,advanced,list,records,inbox)};},actions:{
 'nc-field':c=>send(c,'POST','/definitions',{key:c.form?.['key'],kind:'field',spec:{type:c.form?.['type'],label_fa:c.form?.['label'],public:c.form?.['public']==='true',required:c.form?.['required']==='true',max_length:1000}}),
 'nc-create':c=>guarded(()=>send(c,'POST','/definitions',{key:c.form?.['key'],kind:c.form?.['kind'],spec:parse(c,'spec')}),path),
 'nc-save':c=>guarded(()=>send(c,'PUT','/definitions/'+c.form?.['id'],{expected_version:Number(c.form?.['expected_version']),spec:parse(c,'spec')}),path),
 'nc-record-create':c=>guarded(()=>send(c,'POST','/records',{definition_id:c.form?.['definition_id'],slug:c.form?.['slug'],values:parse(c,'values')}),path),
 'nc-revisions':async c=>{const r=await c.api('GET',base(c,'/definitions/'+c.form?.['id']+'/revisions'));return{page:{title:'نسخه‌های تعریف',status:r.status,html:htmlOf(pageHeader('Compare / Restore — همان تعریف'),card('تاریخچهٔ تغییرناپذیر',tag('pre',{class:'studio-code',dir:'ltr'},escapeText(json(r.json)))),formBlock({id:'nc-restore',action:path+'/nc-restore',csrf:c.csrf,fields:[hidden('id',c.form?.['id']),hidden('expected_version',c.form?.['expected_version']),{name:'revision',label:'شمارهٔ نسخه',required:true,maxLength:8}],submit:'بازگردانی فقط به Draft'}))}};},
 'nc-restore':c=>send(c,'POST','/definitions/'+c.form?.['id']+'/restore',{expected_version:Number(c.form?.['expected_version']),revision:Number(c.form?.['revision'])}),
 'nc-record-save':c=>guarded(()=>send(c,'PUT','/records/'+c.form?.['id'],{expected_version:Number(c.form?.['expected_version']),values:parse(c,'values')}),path),
 'nc-record-delete':c=>send(c,'DELETE','/records/'+c.form?.['id'],{expected_version:Number(c.form?.['expected_version'])}),
 }};}
export const adminNocode=nocodeSection();
export const memberNocode=nocodeSection('pages');
export async function relationshipsBuilder(c:PanelCtx):Promise<string>{const r=await c.api('GET',base(c,'/relationships'));const models=await c.api('GET',base(c));const defs=values(models.json,'definitions').filter(d=>d['kind']==='relationship'&&d['live_enabled']===true);return card('Relationship Builder — تأیید دوطرفه',htmlOf(formBlock({id:'nc-relation',action:'/app/pages/nc-relationship',csrf:c.csrf,fields:[{name:'definition_id',label:'تعریف رابطه',type:'select',options:defs.map(d=>({value:str(d['id']),label:str(d['key'])}))},{name:'target_business_id',label:'شناسهٔ کسب‌وکار عمومی مقصد',dir:'ltr',required:true,maxLength:36},{name:'note',label:'یادداشت درخواست',maxLength:300}],submit:'درخواست رابطه'}),...values(r.json,'items').map(v=>card(str(v['kind'])+' · '+str(v['status']),htmlOf(tag('code',{},escapeText(str(v['id']))),actionForm({action:'/app/pages/nc-relationship-state',csrf:c.csrf,label:'تأیید به‌عنوان گیرنده',hidden:{id:str(v['id']),expected_version:str(v['version']),to:'active'}}),actionForm({action:'/app/pages/nc-relationship-state',csrf:c.csrf,label:'پایان رابطه',hidden:{id:str(v['id']),expected_version:str(v['version']),to:'ended'},tone:'danger'}))))));}
