/* UI استودیو، فقط مشتری API؛ دادهٔ عمل/JSON می‌فرستد و هیچ دروازه‌ای را در مرورگر اجرا نمی‌کند. */
import {tag,escapeText,raw} from '../html.js';
import {describeProblem} from './core.js';
import {card,emptyNote,formBlock,actionForm,pageHeader,dataTable,htmlOf,type Field} from './kit.js';
import type {Section,PanelCtx,ActionOutcome} from './types.js';
type Json=Record<string,unknown>;
const str=(v:unknown)=>v===null||v===undefined?'':String(v);
const arr=(j:Json|null,k:string)=>Array.isArray(j?.[k])?j[k] as Json[]:[];
const json=(v:unknown)=>JSON.stringify(v,null,2);
const base=(c:PanelCtx,p='')=>'/api/v1/studio'+p+(c.surface==='admin'?'?scope=platform':'');
const hidden=(name:string,value:unknown):Field=>({name,label:name,type:'hidden',value:str(value)});
const reauth=(c:PanelCtx)=>card('تأیید هویت برای انتشار',formBlock({id:'studio-reauth',action:'/app/auth/reauth',csrf:c.csrf,fields:[{name:'password',label:'رمز فعلی',type:'password',autocomplete:'current-password',required:true}],submit:'تأیید دوبارهٔ هویت'}));
const parse=(c:PanelCtx,name:string)=>JSON.parse(c.form?.[name]??'{}') as unknown;
const result=(path:string,res:{status:number;json:Json|null;cookies:readonly string[]}):ActionOutcome=>({redirect:path,flash:{kind:res.status>=200&&res.status<300?'success':'error',text:res.status>=200&&res.status<300?'عمل در سرور ثبت شد.':describeProblem(res)}});
function treeNodes(tree:unknown):Array<{id:string;component:string;props:unknown;depth:number}>{const output:Array<{id:string;component:string;props:unknown;depth:number}>=[];const walk=(nodes:Json[],depth:number)=>{for(const n of nodes){output.push({id:str(n['id']),component:str(n['component']),props:n['props']??{},depth});for(const slot of Object.values((n['slots']??{}) as Json))if(Array.isArray(slot))walk(slot as Json[],depth+1);}};if(tree&&typeof tree==='object'&&Array.isArray((tree as Json)['root']))walk((tree as Json)['root'] as Json[],0);return output;}
export function studioSection(key:'pages'|'design'|'tokens'):Section{
 const path='/app/'+key;const title=key==='tokens'?'توکن‌ها و تم':key==='design'?'استودیوی پلتفرم':'صفحه‌ها و طراحی';
 const post=async(c:PanelCtx,method:'POST'|'PUT'|'PATCH'|'DELETE',suffix:string,body:unknown)=>result(path,await c.api(method,base(c,suffix),body));
 return{key,title,async render(c){const response=await c.api('GET',base(c));if(response.status!==200)return {status:response.status,html:htmlOf(pageHeader(title),card('دسترسی به استودیو انجام نشد',emptyNote(describeProblem(response))))};
 const pages=arr(response.json,'pages'),releases=arr(response.json,'releases'),tokens=arr(response.json,'tokens'),themes=arr(response.json,'themes'),components=arr(response.json,'components');
 const selected=pages.find(p=>p['id']===c.url.searchParams.get('page'))??pages[0];let editor='';
 if(selected&&key!=='tokens'){const fetched=await c.api('GET',base(c,'/pages/'+str(selected['id'])));const p=fetched.json?.['page'] as Json|undefined;if(p){
 const nodes=treeNodes(p['draft_tree']);const version=hidden('expected_version',p['version']),id=hidden('id',p['id']);
 editor=card(str(p['title']),htmlOf(
  formBlock({id:'studio-meta',action:path+'/metadata',csrf:c.csrf,fields:[id,version,{name:'title',label:'عنوان سئو',required:true,value:str(selected['has_draft_metadata']?selected['draft_title']:p['title']),maxLength:200},{name:'description',label:'توضیح سئو',type:'textarea',rows:3,maxLength:400,value:str(selected['has_draft_metadata']?selected['draft_description']:p['description'])}],submit:'ذخیرهٔ پیش‌نویس متادیتا'}),
  tag('ol',{class:'studio-outline'},nodes.map(n=>tag('li',{},htmlOf(tag('code',{},escapeText('·'.repeat(n.depth)+' '+n.component+' / '+n.id)),tag('details',{},tag('summary',{},'ویرایش پراپ‌ها')+formBlock({id:'node-'+n.id,action:path+'/node-patch',csrf:c.csrf,fields:[id,version,hidden('node_id',n.id),{name:'props',label:'پراپ‌های داده‌ای',type:'textarea',value:json(n.props),dir:'ltr',rows:4,maxLength:18000}],submit:'ذخیرهٔ گره'})),actionForm({action:path+'/node-remove',csrf:c.csrf,label:'برداشتن گره از Draft',hidden:{id:str(p['id']),node_id:n.id,expected_version:str(p['version'])},tone:'danger'})))).join('')),
  formBlock({id:'studio-add-node',action:path+'/node-add',csrf:c.csrf,fields:[id,version,{name:'component',label:'کامپوننت معنایی',type:'select',options:components.map(v=>({value:str(v['key']),label:str(v['name_fa'])+' — '+str(v['key'])}))},{name:'parent_id',label:'شناسهٔ والد (خالی = ریشه)',dir:'ltr',maxLength:60},{name:'slot',label:'اسلات والد',value:'children',maxLength:60},{name:'props',label:'پراپ‌ها (JSON، بدون HTML/JS/SQL)',type:'textarea',dir:'ltr',value:'{}',rows:5,maxLength:18000,hint:'الگوی هر کامپوننت در راهنمای Registry پایین است.'}],submit:'افزودن گرهٔ Draft'}),
  tag('details',{},tag('summary',{},'ویرایش درخت ساخت‌یافته')+formBlock({id:'studio-tree',action:path+'/save',csrf:c.csrf,fields:[id,version,{name:'tree',label:'درخت نسخهٔ ۱',type:'textarea',value:json(p['draft_tree']),dir:'ltr',rows:12,maxLength:20000},{name:'change_summary',label:'خلاصهٔ تغییر',maxLength:300}],submit:'ذخیرهٔ Draft'}))));}}
 const pageList=card('صفحه‌های این محدوده',dataTable({caption:'صفحه‌ها',columns:[{key:'page',label:'صفحه'},{key:'revision',label:'نسخهٔ پیش‌نویس'},{key:'status',label:'وضعیت'}],rows:pages.map(p=>({page:raw(tag('a',{href:path+'?page='+encodeURIComponent(str(p['id']))},escapeText(str(p['title'])))),revision:str(p['draft_revision']),status:str(p['status'])})),empty:'هنوز صفحه‌ای ساخته نشده است.'}));
 const create=key!=='tokens'?card('ساخت صفحهٔ جدید',formBlock({id:'studio-create',action:path+'/create',csrf:c.csrf,fields:[{name:'key',label:'کلید مسیر (home برای صفحهٔ اصلی)',dir:'ltr',maxLength:60,required:true},{name:'title',label:'عنوان',required:true,maxLength:200}],submit:'ساخت پیش‌نویس'})):'';
 const history=card('انتشارها و بازگشت دقیق',htmlOf(actionForm({action:path+'/prepare',csrf:c.csrf,label:'تهیهٔ بستهٔ Preview از Draft'}),dataTable({caption:'بسته‌های انتشار',columns:[{key:'version',label:'انتشار'},{key:'status',label:'وضعیت'},{key:'hash',label:'SHA-256'},{key:'actions',label:'خط لوله'}],rows:releases.map(r=>({version:str(r['version'])+(r['is_current']?' · جاری':''),status:str(r['status']),hash:raw(tag('code',{},escapeText(str(r['bundle_hash'])))),actions:raw(['validate','preview','report',...(r['status']==='validating'?['approve']:[]),...(r['status']==='approved'?['publish']:[]),...(r['published_at']&&!r['is_current']?['rollback']:[])].map(a=>actionForm({action:path+'/'+a,csrf:c.csrf,label:({validate:'بازرسی',preview:'دیدن Preview',report:'گواه',approve:'تأیید',publish:'انتشار',rollback:'بازگشت دقیق'} as Json)[a] as string,hidden:{id:str(r['id']),expected_version:str(r['lock_version'])},tone:a==='rollback'?'danger':'ghost'}).__html).join(''))})),empty:'بستهٔ انتشار هنوز تهیه نشده است.'})));
 const tokenUi=key==='tokens'||c.surface==='panel'?card('توکن‌های داده‌ای',tokens.filter(t=>t['theme_mode']===(c.url.searchParams.get('mode')??'light')).map(t=>{const owned=c.surface==='admin'||t['business_id']!==null;return tag('details',{},tag('summary',{},escapeText(str(t['key'])+(t['has_draft']?' · Draft':'')))+(owned?formBlock({id:'token-'+str(t['id']),action:path+'/token',csrf:c.csrf,fields:[hidden('id',t['id']),hidden('expected_version',t['version']),{name:'value',label:'مقدار (JSON)',type:'textarea',rows:2,value:json(t['has_draft']?t['draft_value']:t['value']),dir:'ltr',maxLength:2000},{name:'alias_of',label:'ارجاع به توکن',dir:'ltr',value:str(t['has_draft']?t['draft_alias_of']:t['alias_of']),maxLength:120}],submit:'ذخیره فقط در Draft'}):htmlOf(tag('code',{},escapeText(json(t['value']))),actionForm({action:path+'/override',csrf:c.csrf,label:'ساخت نسخهٔ مختص این کسب‌وکار',hidden:{id:str(t['id'])}}))));}).join('')+tag('nav',{'aria-label':'حالت رنگ'},['light','dark','high_contrast'].map(m=>tag('a',{class:'button button--ghost',href:path+'?mode='+m},escapeText(m))).join(''))):'';
 const themeUi=key==='tokens'?card('پیش‌نویس تم',themes.length?themes.map(t=>formBlock({id:'theme-'+str(t['id']),action:path+'/theme',csrf:c.csrf,fields:[hidden('id',t['id']),hidden('expected_version',t['version']),{name:'settings',label:str(t['name_fa']),type:'textarea',value:json(t['draft_settings']??t['settings']),dir:'ltr',rows:8,maxLength:18000}],submit:'ذخیرهٔ Draft تم'})).join(''):emptyNote('تم مختص این محدوده وجود ندارد.')):'';
 const guide=key!=='tokens'?card('Registry؛ قالب پراپ‌ها',components.map(v=>tag('details',{},tag('summary',{},escapeText(str(v['name_fa'])+' — '+str(v['key'])))+tag('pre',{class:'studio-code',dir:'ltr'},escapeText(json(v['props_schema']))))).join('')):'';
 return{html:htmlOf(pageHeader(title,{subtitle:'Draft → Preview → Validation → Approval → Publish. تغییر Draft هیچ اثری بر سایت عمومی ندارد.'}),key!=='tokens'?pageList:'',create,editor,tokenUi,themeUi,history,reauth(c),guide)};},
 actions:{
 create:c=>post(c,'POST','/pages',{key:c.form?.['key'],title:c.form?.['title']}),
 save:async c=>{try{return await post(c,'PUT','/pages/'+c.form?.['id'],{tree:parse(c,'tree'),expected_version:Number(c.form?.['expected_version']),change_summary:c.form?.['change_summary']});}catch{return{redirect:path,flash:{kind:'error',text:'JSON درخت خوانا نیست.'}};}},
 metadata:c=>post(c,'PUT','/pages/'+c.form?.['id']+'/metadata',{expected_version:Number(c.form?.['expected_version']),title:c.form?.['title'],description:c.form?.['description']}),
 'node-add':async c=>{try{return await post(c,'POST','/pages/'+c.form?.['id']+'/nodes',{expected_version:Number(c.form?.['expected_version']),component:c.form?.['component'],parent_id:c.form?.['parent_id']||null,slot:c.form?.['slot']||'children',props:parse(c,'props')});}catch{return{redirect:path,flash:{kind:'error',text:'JSON پراپ‌ها خوانا نیست.'}};}},
 'node-patch':async c=>{try{return await post(c,'PATCH','/pages/'+c.form?.['id']+'/nodes/'+c.form?.['node_id'],{expected_version:Number(c.form?.['expected_version']),props:parse(c,'props')});}catch{return{redirect:path,flash:{kind:'error',text:'JSON پراپ‌ها خوانا نیست.'}};}},
 'node-remove':c=>post(c,'DELETE','/pages/'+c.form?.['id']+'/nodes/'+c.form?.['node_id'],{expected_version:Number(c.form?.['expected_version'])}),
 token:async c=>{try{return await post(c,'PUT','/tokens/'+c.form?.['id'],{expected_version:Number(c.form?.['expected_version']),value:parse(c,'value'),alias_of:c.form?.['alias_of']||null});}catch{return{redirect:path,flash:{kind:'error',text:'JSON توکن خوانا نیست.'}};}},
 override:c=>post(c,'POST','/tokens/'+c.form?.['id']+'/override',{}),
 theme:async c=>{try{return await post(c,'PUT','/themes/'+c.form?.['id'],{expected_version:Number(c.form?.['expected_version']),settings:parse(c,'settings')});}catch{return{redirect:path,flash:{kind:'error',text:'JSON تم خوانا نیست.'}};}},
 prepare:c=>post(c,'POST','/releases',{}),
 validate:c=>post(c,'POST','/releases/'+c.form?.['id']+'/validate',{}),
 approve:c=>post(c,'POST','/releases/'+c.form?.['id']+'/approve',{expected_version:Number(c.form?.['expected_version'])}),
 publish:c=>post(c,'POST','/releases/'+c.form?.['id']+'/publish',{expected_version:Number(c.form?.['expected_version'])}),
 rollback:c=>post(c,'POST','/releases/'+c.form?.['id']+'/rollback',{expected_version:Number(c.form?.['expected_version'])}),
 preview:async c=>{const response=await c.api('POST',base(c,'/releases/'+c.form?.['id']+'/preview'),{});if(response.status!==200)return result(path,response);const preview=response.json?.['preview'] as Json;return{page:{title:'Preview خصوصیِ همان Snapshot',themeCss:str(preview['css']),previewDoc:str(preview['document']),html:htmlOf(pageHeader('Preview؛ هنوز عمومی نشده'),tag('p',{},escapeText(str(preview['path']))),tag('a',{class:'button',href:path},'بازگشت به خط لوله'))}};},
 report:async c=>{const response=await c.api('GET',base(c,'/releases/'+c.form?.['id']));if(response.status!==200)return result(path,response);const release=response.json?.['release'] as Json;return{page:{title:'گواه واقعیِ انتشار',html:htmlOf(pageHeader('گواه انتشار'),tag('p',{},escapeText(str(release['bundle_hash']))),card('Stageها و شواهد',tag('pre',{class:'studio-code',dir:'ltr'},escapeText(json(release['validation_report'])))),tag('a',{class:'button',href:path},'بازگشت'))}};},
 }};
}
export const pagesSection=studioSection('pages');
