/* Adapter قابل تعویض؛ نتایج remote همیشه باید دوباره با DB مجاز/تازه تطبیق شوند. */
export type SearchDriver='postgres'|'opensearch'|'elasticsearch'|'meilisearch';
export interface SearchHit {id:string;entity_kind:string;entity_id:string;title:string;snippet:string;path:string;business_id:string|null;rank:number}
export interface SearchOptions {query:string;limit:number;cursor?:string|null;kind?:string|null}
export interface SearchAdapter {status():{driver:SearchDriver;state:'configured'|'not_configured';reason?:string};search(options:SearchOptions):Promise<SearchHit[]>}
export function postgresSearchAdapter(query:(options:SearchOptions)=>Promise<SearchHit[]>):SearchAdapter{return{status:()=>({driver:'postgres',state:'configured'}),search:query};}
export function remoteSearchAdapter(options:{driver:Exclude<SearchDriver,'postgres'>;endpoint?:string;key?:string;index?:string;fetch?:typeof fetch;authorize:(ids:string[])=>Promise<SearchHit[]>}):SearchAdapter{
 const {driver,endpoint,key}=options;const reason=!endpoint?'SEARCH_ENDPOINT missing':!key?'SEARCH_API_KEY missing':null;
 return{status:()=>reason?{driver,state:'not_configured',reason}:{driver,state:'configured'},async search(input){if(reason)throw new Error('search_not_configured: '+reason);const base=new URL(endpoint!);if(!['http:','https:'].includes(base.protocol))throw new Error('unsafe_search_endpoint');let url:URL,body:unknown,headers:Record<string,string>={'content-type':'application/json'};
 if(driver==='meilisearch'){url=new URL('/indexes/'+encodeURIComponent(options.index??'petavu-public')+'/search',base);headers['authorization']='Bearer '+key;body={q:input.query,limit:Math.min(input.limit,50),filter:['is_public = true',...(input.kind?[`entity_kind = ${JSON.stringify(input.kind)}`]:[])]};}
 else{url=new URL('/'+encodeURIComponent(options.index??'petavu-public')+'/_search',base);headers['authorization']='ApiKey '+key;body={size:Math.min(input.limit,50),query:{bool:{must:[{multi_match:{query:input.query,fields:['title^3','normalized_text']}}],filter:[{term:{is_public:true}},...(input.kind?[{term:{entity_kind:input.kind}}]:[])]}},_source:['id']};}
 const response=await(options.fetch??fetch)(url,{method:'POST',headers,body:JSON.stringify(body),redirect:'error',signal:AbortSignal.timeout(5000)});if(!response.ok)throw new Error('search_provider_http_'+response.status);const data=await response.json() as Record<string,unknown>;const hits=driver==='meilisearch'?data['hits'] as Array<Record<string,unknown>>:((data['hits'] as Record<string,unknown>)['hits'] as Array<Record<string,unknown>>).map(h=>(h['_source']??h) as Record<string,unknown>);const ids=hits.map(h=>String(h['id']??'')).filter(v=>/^[0-9a-f-]{36}$/i.test(v));return options.authorize(ids.slice(0,50));}};
}
