import {AppError,newOpaqueToken,uuidv7} from '@petavu/shared';
import {mintSessionToken,sessionCookie,csrfCookie,issueCsrfToken,clearCookie,newTotpSecret,credentialKey,sealCredential,openCredential,verifyTotp,hashToken,generateRegistrationOptions,verifyRegistrationResponse,generateAuthenticationOptions,verifyAuthenticationResponse,type RegistrationResponseJSON,type AuthenticationResponseJSON} from '@petavu/security';
import {cookieNames} from '../cookies.js';
import type {Scope,RouteDefinition} from '../types.js';import {validator} from '../validate.js';
type J=Record<string,unknown>;
export async function verifySecondFactor(s:Scope,userId:string|null,code:string|null,recovery:string|null,forceStaff=false):Promise<{ok:boolean;aal:number;required:boolean}>{const [row]=await s.query<{material:J}>('select app.auth_mfa_material($1::uuid) material',[userId]);const m=row?.material??{};const required=m['required']===true||(forceStaff&&m['staff']===true);if(!required)return{ok:true,aal:1,required:false};if(recovery){const [used]=await s.query<{ok:boolean}>('select app.consume_recovery($1::uuid,$2) ok',[m['user_id'],hashToken(recovery.replace(/[- ]/g,'').toUpperCase())]);return{ok:used?.ok===true,aal:2,required:true};}const factor=m['totp'] as J|null;if(!factor||!code)return{ok:false,aal:1,required:true};const secret=openCredential(String(factor['cipher']),credentialKey(s.services.env.security.sessionSecret,s.services.env.isProduction));const counter=verifyTotp(secret,code,s.services.now());if(counter===null)return{ok:false,aal:1,required:true};const [used]=await s.query<{ok:boolean}>('select app.consume_totp($1::uuid,$2) ok',[m['user_id'],counter]);return{ok:used?.ok===true,aal:2,required:true};}
const definition=(path:string,name:string,summary:string,handler:RouteDefinition['handler']):RouteDefinition=>({method:'POST',path:'/api/v1/auth/'+path,name:'mfa.'+name,summary,tags:['auth'],auth:'session',role:'pv_app',handler});
export const mfaRoutes:RouteDefinition[]=[
definition('mfa/setup','setup','ساخت TOTP ciphertext و challenge؛ secret فقط همین بار',async(r,s)=>{await s.query('select app.require_recent_auth()');const secret=newTotpSecret(),cipher=sealCredential(secret,credentialKey(s.services.env.security.sessionSecret,s.services.env.isProduction));const [row]=await s.query<{challenge:J}>('select app.create_auth_challenge(\'totp_setup\',$1,$2::jsonb) challenge',[newOpaqueToken(32),JSON.stringify({cipher})]);return{status:200,body:{challenge:row?.challenge,secret,uri:'otpauth://totp/PETAVU:'+encodeURIComponent(r.auth.kind==='session'?r.auth.displayName:'user')+'?secret='+secret+'&issuer=PETAVU&algorithm=SHA1&digits=6&period=30'}};}),
definition('mfa/confirm','confirm','اثبات واقعی TOTP، یک‌بارمصرف و atomic',async(r,s)=>{const v=validator(r.body),id=v.uuid('challenge_id'),code=v.string('code',{min:6,max:6});v.done();const [row]=await s.query<{challenge:J|null}>('select app.own_auth_challenge($1,\'totp_setup\') challenge',[id]);if(!row?.challenge)throw new AppError('precondition_failed');const material=row.challenge['material'] as J,secret=openCredential(String(material['cipher']),credentialKey(s.services.env.security.sessionSecret,s.services.env.isProduction));const counter=verifyTotp(secret,code,s.services.now());if(counter===null)throw new AppError('unauthenticated');await s.query('select app.finish_auth_challenge($1,\'totp_setup\',null,$2,$3::jsonb)',[id,material['cipher'],JSON.stringify({last_counter:counter})]);await s.query('select app.complete_reauth_mfa(true,2::smallint)');return{status:200,body:{enabled:true}};}),
definition('mfa/recovery','recovery','کدهای یک‌بارمصرف؛ فقط hash در DB، نمایش تنها یک‌بار',async(_r,s)=>{await s.query('select app.require_recent_auth()');const codes=Array.from({length:10},()=>newOpaqueToken(12).replace(/[^A-Za-z0-9]/g,'').toUpperCase());await s.query('select app.mfa_recovery_codes($1::jsonb)',[JSON.stringify(codes.map(hashToken))]);return{status:200,body:{codes,note:'فقط یک‌بار نشان داده می‌شوند؛ در محل امن آفلاین نگهداری کنید.'}};}),
definition('passkeys/options','passkeyOptions','WebAuthn registration، Origin/RPID/challenge واقعی',async(r,s)=>{if(r.auth.kind!=='session'||!r.origin)throw new AppError('unauthenticated');await s.query('select app.require_recent_auth()');const rpID=new URL(r.origin).hostname;const options=await generateRegistrationOptions({rpName:'PETAVU',rpID,userID:new Uint8Array([...Buffer.from(r.auth.userId)]),userName:r.auth.displayName,attestationType:'none',authenticatorSelection:{userVerification:'required',residentKey:'preferred'}});const [row]=await s.query<{challenge:J}>('select app.create_auth_challenge(\'webauthn_register\',$1,$2::jsonb) challenge',[options.challenge,JSON.stringify({rpID,origin:r.origin})]);return{status:200,body:{options,challenge_id:row?.challenge['id']}};}),
definition('passkeys/register','passkeyRegister','تأیید attestation/UV و ذخیرهٔ public key، نه private key',async(r,s)=>{const v=validator(r.body),id=v.uuid('challenge_id'),response=v.object('response');v.done();const [row]=await s.query<{c:J|null}>('select app.own_auth_challenge($1,\'webauthn_register\') c',[id]);if(!row?.c)throw new AppError('precondition_failed');const material=row.c['material'] as J;const verified=await verifyRegistrationResponse({response:response as unknown as RegistrationResponseJSON,expectedChallenge:String(row.c['challenge']),expectedOrigin:String(material['origin']),expectedRPID:String(material['rpID']),requireUserVerification:true});if(!verified.verified||!verified.registrationInfo)throw new AppError('unauthenticated');const credential=verified.registrationInfo.credential;await s.query('select app.finish_auth_challenge($1,\'webauthn_register\',$2,$3,$4::jsonb)',[id,credential.id,'public-key:'+Buffer.from(credential.publicKey).toString('base64url'),JSON.stringify({publicKey:Buffer.from(credential.publicKey).toString('base64url'),counter:credential.counter,rpID:material['rpID'],transports:credential.transports??[]})]);await s.query('select app.complete_reauth_mfa(true,2::smallint)');return{status:200,body:{registered:true}};}),
definition('passkeys/auth/options','passkeyAuthOptions','Challenge WebAuthn برای step-up',async(r,s)=>{if(!r.origin)throw new AppError('forbidden');const [m]=await s.query<{m:J}>('select app.auth_mfa_material(null) m');const keys=(m?.m['webauthn']??[]) as J[];const rpID=new URL(r.origin).hostname,options=await generateAuthenticationOptions({rpID,userVerification:'required',allowCredentials:keys.filter(k=>(k['params'] as J)['rpID']===rpID).map(k=>({id:String(k['external_id'])}))});const [row]=await s.query<{challenge:J}>('select app.create_auth_challenge(\'webauthn_authenticate\',$1,$2::jsonb) challenge',[options.challenge,JSON.stringify({rpID,origin:r.origin})]);return{status:200,body:{options,challenge_id:row?.challenge['id']}};}),
definition('passkeys/auth/verify','passkeyAuthVerify','تأیید signature/counter/UV، بدون bypass',async(r,s)=>{const v=validator(r.body),id=v.uuid('challenge_id'),response=v.object('response');v.done();const [row]=await s.query<{c:J|null}>('select app.own_auth_challenge($1,\'webauthn_authenticate\') c',[id]);if(!row?.c)throw new AppError('precondition_failed');const [m]=await s.query<{m:J}>('select app.auth_mfa_material(null) m');const key=((m?.m['webauthn']??[]) as J[]).find(k=>k['external_id']===response['id']);if(!key)throw new AppError('unauthenticated');const params=key['params'] as J,material=row.c['material'] as J;const checked=await verifyAuthenticationResponse({response:response as unknown as AuthenticationResponseJSON,expectedChallenge:String(row.c['challenge']),expectedOrigin:String(material['origin']),expectedRPID:String(material['rpID']),credential:{id:String(key['external_id']),publicKey:new Uint8Array(Buffer.from(String(params['publicKey']),'base64url')),counter:Number(params['counter'])},requireUserVerification:true});if(!checked.verified)throw new AppError('unauthenticated');const [ok]=await s.query<{ok:boolean}>('select app.update_passkey_counter($1,$2) ok',[key['id'],checked.authenticationInfo.newCounter]);if(!ok?.ok)throw new AppError('unauthenticated');await s.query('select app.consume_auth_challenge($1)',[id]);await s.query('select app.complete_reauth_mfa(true,2::smallint)');return{status:200,body:{verified:true}};}),
];
mfaRoutes.push({method:'GET',path:'/api/v1/auth/mfa/status',name:'mfa.status',summary:'وضعیت MFA بدون secret/key/cipher',tags:['auth'],auth:'session',role:'pv_app',handler:async(_r,s)=>{const [row]=await s.query<{m:J}>('select app.auth_mfa_material(null) m');const m=row?.m??{};return{body:{required:m['required']===true,totp_enabled:Boolean(m['totp']),passkeys:((m['webauthn']??[]) as J[]).map(k=>({id:k['id'],rp_id:(k['params'] as J)['rpID']}))}};}});

mfaRoutes.push(definition('impersonation/start','impersonate','ورود با اختیار کاربر: ۱۵ دقیقه، reason، re-auth و audit',async(r,s)=>{const v=validator(r.body),target=v.uuid('user_id'),reason=v.string('reason',{min:5,max:500});v.done();const sid=uuidv7(),token=mintSessionToken(sid);const [row]=await s.query('select app.start_impersonation($1,$2,$3,$4) started',[target,sid,token.secretHash,reason]);const csrf=issueCsrfToken({secret:s.services.env.security.sessionSecret,sessionId:sid,nowMs:s.services.now()});const names=cookieNames(s.services.env);return{status:200,body:{started:row?.['started'],csrf_token:csrf,notice:'ورود با اختیار فعال است؛ تغییر credential/role ممنوع و پایان نیازمند ورود مجدد کارمند است.'},cookies:[sessionCookie(names.session,token.token,{secure:s.services.env.isProduction,maxAgeSeconds:900}),csrfCookie(names.csrf,csrf,{secure:s.services.env.isProduction,maxAgeSeconds:900})]};}));
mfaRoutes.push(definition('impersonation/stop','stopImpersonate','پایان ورود با اختیار، بدون نگهداری secret کارمند در مرورگر',async(_r,s)=>{await s.query('select app.stop_impersonation()');const names=cookieNames(s.services.env);return{status:200,body:{stopped:true,relogin_required:true},cookies:[clearCookie(names.session,{secure:s.services.env.isProduction}),clearCookie(names.csrf,{secure:s.services.env.isProduction})]};}));
