/* No-Code روی همان content، design release، مجوز و outbox؛ نه پایگاه‌داده/Workflow دوم. */
import {AppError,isUuid} from '@petavu/shared';
import {FIELD_TYPES,validateDefinition,validateValues,definitionFields,publicProjection,type Definition,type DefinitionKind} from '@petavu/design/nocode';
import type {ApiRequest,Scope,RouteDefinition} from '../types.js';
import {validator} from '../validate.js';
type Json=Record<string,unknown>;
const uuid=(value:unknown)=>{if(!isUuid(value))throw new AppError('validation_failed');return value;};
async function scopeOf(r:ApiRequest,s:Scope,manage=true):Promise<string|null>{const requested=r.query.get('scope');if(requested&&!['business','platform'].includes(requested))throw new AppError('validation_failed');const b=requested==='platform'?null:r.auth.kind==='session'?r.auth.activeBusinessId:null;if(requested!=='platform'&&(!b||b!==r.businessId))throw new AppError('forbidden');if(manage)await s.query('select design.assert_access($1::uuid)',[b]);else if(b===null){const [p]=await s.query<{yes:boolean}>("select app.has_platform_permission('platform.content.moderate') yes");if(!p?.yes)throw new AppError('forbidden');}else{const [p]=await s.query<{yes:boolean}>('select app.is_member_of($1) yes',[b]);if(!p?.yes)throw new AppError('forbidden');}if(!manage)await s.query("select pg_advisory_xact_lock_shared(hashtextextended(coalesce($1::text,'platform')||'.design',0))",[b]);return b;}
async function definitions(s:Scope,b:string|null,drafts=true):Promise<Definition[]>{const [row]=await s.query<{items:Definition[]}>('select design.list_definitions($1::uuid,$2) items',[b,drafts]);return row?.items??[];}
async function definition(r:ApiRequest,s:Scope,drafts=true){const b=await scopeOf(r,s,drafts);const def=(await definitions(s,b,drafts)).find(d=>d.id===uuid(r.params['id']));if(!def)throw new AppError('not_found');return {b,def};}
async function requirePermission(s:Scope,b:string|null,key:string){const [p]=await s.query<{yes:boolean}>(b?'select app.has_permission($1,$2) yes':"select app.has_platform_permission('platform.content.moderate') yes",b?[b,key]:[]);if(!p?.yes)throw new AppError('forbidden');}
async function verifyRefs(s:Scope,b:string|null,fields:Definition[],values:Json,publicOnly=false){for(const f of fields){const value=values[f.key];if(!value)continue;if(f.spec['type']==='asset'){const [asset]=await s.query('select id from media.asset where id=$1::uuid and status=\'ready\' and deleted_at is null and (business_id is null or business_id is not distinct from $2::uuid) and (not $3 or is_public)',[value,b,publicOnly||f.spec['public']===true]);if(!asset)throw new AppError('validation_failed');}else if(f.spec['type']==='reference'){const [ref]=await s.query('select c.id from app.content c join app.content_extension e on e.content_id=c.id where c.id=$1::uuid and e.definition_id=$2::uuid and c.business_id is not distinct from $3::uuid and c.deleted_at is null and (not $4 or (c.status=\'published\' and c.visibility=\'public\'))',[value,f.spec['reference_model'],b,publicOnly||f.spec['public']===true]);if(!ref)throw new AppError('validation_failed');}}}
async function vetReferences(s:Scope,b:string|null,kind:DefinitionKind,spec:Json){if(['form','crud'].includes(kind)){const defs=await definitions(s,b);const fields=definitionFields({id:'',business_id:b,key:'',kind,spec,version:1},defs);if(kind==='crud')for(const key of [spec['title_field'],spec['summary_field'],...((spec['search_fields']??[]) as unknown[])].filter(v=>v!==undefined))if(!fields.some(f=>f.key===key&&f.spec['public']===true&&f.spec['sensitive']!==true))throw new AppError('validation_failed');}if(spec['read_permission']){const [p]=await s.query('select key from auth.permission where key=$1 and scope<>\'platform\'',[spec['read_permission']]);if(!p)throw new AppError('validation_failed');}}
async function record(r:ApiRequest,s:Scope){const b=await scopeOf(r,s,false);await requirePermission(s,b,'content.update');const [c]=await s.query('select c.id,c.business_id,c.kind,c.slug,c.title,c.summary,c.status,c.version,e.definition_id,e.values from app.content c join app.content_extension e on e.content_id=c.id where c.id=$1::uuid and c.business_id is not distinct from $2::uuid and c.deleted_at is null',[uuid(r.params['id']),b]);if(!c)throw new AppError('not_found');const defs=await definitions(s,b,false),def=defs.find(d=>d.id===c['definition_id']);if(!def||def.kind!=='crud')throw new AppError('precondition_failed');return {b,c,def,fields:definitionFields(def,defs)};}
const route=(method:RouteDefinition['method'],path:string,name:string,summary:string,handler:RouteDefinition['handler']):RouteDefinition=>({method,path:'/api/v1/nocode'+path,name:'nocode.'+name,summary,tags:['nocode'],auth:'session',role:'pv_app',handler});
export const nocodeRoutes:RouteDefinition[]=[
route('GET','', 'overview','Field/Relationship/Form/CRUD؛ Scope و Draft به‌عنوان داده',async(r,s)=>{const b=await scopeOf(r,s);return {body:{scope:b,types:FIELD_TYPES,definitions:await definitions(s,b),publish_via:'/api/v1/studio/releases'}};}),
route('POST','/definitions','create','ساخت تعریف محدود بدون DDL یا کد',async(r,s)=>{const b=await scopeOf(r,s),v=validator(r.body),key=v.string('key',{min:2,max:60}),kind=v.string('kind',{min:4,max:20}) as DefinitionKind,spec=v.object('spec');v.done();if(!/^[a-z][a-z0-9_]{1,59}$/.test(key))throw new AppError('validation_failed');validateDefinition(kind,spec);await vetReferences(s,b,kind,spec);const [row]=await s.query('select design.create_definition($1::uuid,$2,$3,$4::jsonb) definition',[b,key,kind,JSON.stringify(spec)]);return {status:201,body:row??{}};}),
route('PUT','/definitions/:id','save','پیش‌نویس نسخه‌دارِ تعریف',async(r,s)=>{const {b,def}=await definition(r,s),v=validator(r.body),version=v.integer('expected_version',{min:1}),spec=v.object('spec');v.done();validateDefinition(def.kind,spec);await vetReferences(s,b,def.kind,spec);const [row]=await s.query('select design.save_definition($1::uuid,$2,$3::jsonb) definition',[def.id,version,JSON.stringify(spec)]);return {status:200,body:row??{}};}),
route('GET','/definitions/:id/revisions','revisions','نسخه و مقایسهٔ تنظیمات',async(r,s)=>{const {def}=await definition(r,s);return {body:{items:await s.query('select revision,spec,spec_hash,created_at from design.definition_revision where definition_id=$1 order by revision desc limit 30',[def.id])}};}),
route('POST','/definitions/:id/restore','restore','نسخهٔ قدیمی فقط به Draft بازمی‌گردد',async(r,s)=>{const {def}=await definition(r,s),v=validator(r.body),version=v.integer('expected_version',{min:1}),revision=v.integer('revision',{min:1});v.done();const [old]=await s.query('select spec from design.definition_revision where definition_id=$1 and revision=$2',[def.id,revision]);if(!old)throw new AppError('not_found');const [row]=await s.query('select design.save_definition($1::uuid,$2,$3::jsonb) definition',[def.id,version,JSON.stringify(old['spec'])]);return {status:200,body:row??{}};}),
route('GET','/records','records','فهرست CRUD با همان content و صفحه‌بندی نشانگری',async(r,s)=>{const b=await scopeOf(r,s,false);await requirePermission(s,b,'content.update');const id=uuid(r.query.get('definition_id'));const items=await s.query('select c.id,c.title,c.slug,c.kind,c.status,c.version,c.created_at from app.content c join app.content_extension e on e.content_id=c.id where e.definition_id=$1 and c.business_id is not distinct from $2::uuid and c.deleted_at is null and ($3::uuid is null or c.id<$3::uuid) order by c.id desc limit 25',[id,b,r.query.get('cursor')?uuid(r.query.get('cursor')):null]);return {body:{items:items.slice(0,24),next_cursor:items.length>24?items[23]?.['id']:null}};}),
route('POST','/records','recordCreate','CRUD روی موجودیت content؛ دادهٔ خصوصی بیرون از سطر عمومی',async(r,s)=>{const b=await scopeOf(r,s,false);await requirePermission(s,b,'content.create');const v=validator(r.body),id=v.uuid('definition_id'),slug=v.string('slug',{min:2,max:120}),input=v.object('values');v.done();const defs=await definitions(s,b,false),def=defs.find(d=>d.id===id&&d.kind==='crud'&&d.business_id===b);if(!def)throw new AppError('not_found');const fields=definitionFields(def,defs),values=validateValues(fields,input,true);await verifyRefs(s,b,fields,values);const title=String(values[String(def.spec['title_field'])]??'');if(title.length<2||title.length>200)throw new AppError('validation_failed');const projection=publicProjection(fields,values);const content=b?await s.repos.content.create(b,{kind:String(def.spec['content_kind']),slug,title,summary:def.spec['summary_field']?String(values[String(def.spec['summary_field'])]??'').slice(0,600):null,body:{type:'doc',blocks:projection.blocks},bodyText:projection.text}):(await s.query('insert into app.content(business_id,kind,slug,title,summary,body,body_text,author_user_id) values(null,$1,$2,$3,$4,$5::jsonb,$6,$7) returning id,slug,title,status,version',[def.spec['content_kind'],slug,title,def.spec['summary_field']?String(values[String(def.spec['summary_field'])]??'').slice(0,600):null,JSON.stringify({type:'doc',blocks:projection.blocks}),projection.text,r.auth.kind==='session'?r.auth.userId:null]))[0]!;await s.query('insert into app.content_extension(content_id,business_id,definition_id,values) values($1,$2,$3,$4::jsonb)',[content['id'],b,id,JSON.stringify(values)]);await s.query('select app.nocode_metadata($1::uuid)',[content['id']]);await s.query("select app.record_audit('nocode.record_created','content',$1,$2::uuid),app.emit_event('content.created','content',$1,$2::uuid,$3::jsonb)",[content['id'],b,JSON.stringify({definition_id:id,content_id:content['id']})]);return {status:201,body:{record:content}};}),
route('GET','/records/:id','record','ویرایش مجاز دادهٔ خصوصی و عمومی',async(r,s)=>{const {b,c,fields}=await record(r,s);const values={...(c['values'] as Json)};for(const f of fields)if(f.spec['read_permission']){const [p]=await s.query<{yes:boolean}>('select app.has_permission($1,$2) yes',[b,f.spec['read_permission']]);if(!p?.yes)delete values[f.key];}return {body:{record:{...c,values},fields}};}),
route('PUT','/records/:id','recordSave','به‌روزرسانی اتمی نسخه‌دار + projection فقط عمومی',async(r,s)=>{const {b,c,def,fields}=await record(r,s),v=validator(r.body),version=v.integer('expected_version',{min:1}),input=v.object('values');v.done();for(const f of fields)if(input[f.key]!==undefined&&f.spec['read_permission'])await requirePermission(s,b,String(f.spec['read_permission']));const values=validateValues(fields,{...(c['values'] as Json),...input},true);await verifyRefs(s,b,fields,values);const projection=publicProjection(fields,values);const updated=await s.repos.content.update(String(c['id']),version,{title:String(values[String(def.spec['title_field'])]),summary:def.spec['summary_field']?String(values[String(def.spec['summary_field'])]??'').slice(0,600):null,body:{type:'doc',blocks:projection.blocks},body_text:projection.text});await s.query('update app.content_extension set values=$1::jsonb where content_id=$2',[JSON.stringify(values),c['id']]);await s.query("select app.record_audit('nocode.record_updated','content',$1,$2::uuid),app.emit_event('content.updated','content',$1,$2::uuid)",[c['id'],b]);return {status:200,body:{record:updated}};}),
route('DELETE','/records/:id','recordDelete','حذف نرم؛ نگهداشت داده را جعل نمی‌کند',async(r,s)=>{const {b,c}=await record(r,s);await requirePermission(s,b,'content.delete');const v=validator(r.body),version=v.integer('expected_version',{min:1});v.done();const [updated]=await s.query('update app.content set deleted_at=now() where id=$1 and version=$2 returning id,version',[c['id'],version]);if(!updated)throw new AppError('conflict');await s.query("select app.record_audit('nocode.record_deleted','content',$1,$2::uuid),app.emit_event('content.deleted','content',$1,$2::uuid)",[c['id'],b]);return {status:200,body:{record:updated}};}),
route('GET','/submissions','submissions','درخواست‌های واقعی؛ هرگز عمومی نیستند',async(r,s)=>{const b=await scopeOf(r,s);return {body:{items:await s.query('select id,form_id,schema_hash,values,consented,created_at,request_id from app.form_submission where business_id is not distinct from $1::uuid order by created_at desc,id desc limit 30',[b])}};}),
route('GET','/relationships','relationships','همان گراف B2B، با pending برای طرف‌های مجاز',async(r,s)=>{const b=await scopeOf(r,s,false);await requirePermission(s,b,'business.relationship.manage');return {body:{items:await s.query('select r.id,r.from_business_id,r.to_business_id,r.kind,r.status,r.version,r.note,r.created_at from app.business_relationship r where from_business_id=$1 or to_business_id=$1 order by created_at desc,id desc limit 30',[b])}};}),
route('POST','/relationships','relationshipCreate','Relationship Builder روی گراف موجود',async(r,s)=>{const b=await scopeOf(r,s,false);await requirePermission(s,b,'business.relationship.manage');const v=validator(r.body),definitionId=v.uuid('definition_id'),target=v.uuid('target_business_id'),note=v.optionalString('note',{max:300});v.done();const [row]=await s.query('select app.request_nocode_relationship($1::uuid,$2::uuid,$3) relationship',[definitionId,target,note]);return {status:201,body:row??{}};}),
route('POST','/relationships/:id/state','relationshipState','تأیید فقط توسط گیرنده + optimistic concurrency',async(r,s)=>{await scopeOf(r,s,false);const v=validator(r.body),version=v.integer('expected_version',{min:1}),to=v.string('to',{min:3,max:10});v.done();const [row]=await s.query('select app.relationship_state($1::uuid,$2,$3) relationship',[uuid(r.params['id']),version,to]);return {status:200,body:row??{}};}),
];
for(const receiver of [false,true])nocodeRoutes.push({method:'POST',path:receiver?'/api/v1/public/businesses/:businessId/forms/:id/submissions':'/api/v1/public/forms/:id/submissions',name:receiver?'nocode.publicBusinessSubmit':'nocode.publicSubmit',summary:'ثبت واقعی فرم عمومی، consent/ضداسپم/نسخه/محدوده/تکرار',tags:['nocode'],auth:'public',role:'pv_public',rateLimit:{name:'public_form_submit',limit:12,windowMs:600000},handler:async(r,s)=>{if(!r.origin||!s.services.env.origins.public||r.origin!==s.services.env.origins.public)throw new AppError('forbidden');const business=receiver?uuid(r.params['businessId']):null,id=uuid(r.params['id']),v=validator(r.body),key=v.uuid('idempotency_key'),hash=v.string('schema_hash',{min:70,max:80}),consent=v.boolean('consent'),input=v.object('values'),trap=v.optionalString('website',{max:100});v.done();if(trap||!consent)throw new AppError('validation_failed');const [row]=await s.query<{schema:Json|null}>('select design.public_form($1::uuid,$2::uuid) schema',[id,business]);if(!row?.schema)throw new AppError('not_found');const fields=row.schema['fields'] as Definition[],values=validateValues(fields,input,true);await verifyRefs(s,business,fields,values,true);const [result]=await s.query('select app.submit_nocode_form($1::uuid,$2::uuid,$3,$4::jsonb,$5,$6::uuid) id',[id,business,hash,JSON.stringify(values),true,key]);return {status:201,body:{stored:true,id:result?.['id'],success_message:(row.schema['form'] as Definition).spec['success_message']??'درخواست شما ثبت شد.'}};}});
