import {AppError,isUuid} from '@petavu/shared';import {validator} from '../validate.js';import type {RouteDefinition,ApiRequest,Scope} from '../types.js';
const id=(v:unknown)=>{if(!isUuid(v))throw new AppError('validation_failed');return v;};
async function business(r:ApiRequest,s:Scope,permission:string){if(r.auth.kind!=='session'||!r.auth.activeBusinessId||r.businessId!==r.auth.activeBusinessId)throw new AppError('forbidden');const [row]=await s.query<{b:string}>('select app.shop_assert($1) b',[permission]);return row!.b;}
const COLUMNS='id,business_id,sku,title,description,price_minor::text,currency,stock_qty,reserved_qty,status,version';
export const shopRoutes:RouteDefinition[]=[
{method:'GET',path:'/api/v1/shop/products',name:'shop.products',summary:'کاتالوگ واقعی B2B، cursor و فقط فروشندهٔ عمومی',tags:['shop'],auth:'public',role:'pv_public',handler:async(r,s)=>{const cursor=r.query.get('cursor');if(cursor&&!isUuid(cursor))throw new AppError('validation_failed');const rows=await s.query(`select ${COLUMNS} from app.shop_product where status='published' and ($1::uuid is null or id>$1) order by id limit 25`,[cursor]);return {body:{items:rows.slice(0,24),next_cursor:rows.length>24?rows[23]?.['id']:null}};}},
{method:'GET',path:'/api/v1/shop/products/:id',name:'shop.product',summary:'محصول عمومی؛ نه پیش‌نویس فروشنده',tags:['shop'],auth:'public',role:'pv_public',handler:async(r,s)=>{const [p]=await s.query(`select ${COLUMNS} from app.shop_product where id=$1 and status='published'`,[id(r.params['id'])]);if(!p)throw new AppError('not_found');return{body:{product:p}};}},
{method:'GET',path:'/api/v1/shop/manage/products',name:'shop.manageProducts',summary:'محصول‌های فروشندهٔ فعال با مجوز سرور',tags:['shop'],auth:'session',role:'pv_app',handler:async(r,s)=>{const b=await business(r,s,'shop.manage');return{body:{items:await s.query(`select ${COLUMNS} from app.shop_product where business_id=$1 order by id limit 100`,[b])}};}},
{method:'POST',path:'/api/v1/shop/manage/products',name:'shop.createProduct',summary:'ساخت محصول Draft؛ هیچ موجودی یا پرداخت جعلی ایجاد نمی‌شود',tags:['shop'],auth:'session',role:'pv_app',handler:async(r,s)=>{const b=await business(r,s,'shop.manage'),v=validator(r.body),sku=v.string('sku',{min:2,max:80}),title=v.string('title',{min:2,max:200}),description=v.optionalString('description',{max:4000}),minor=v.string('price_minor',{min:1,max:13}),currency=v.string('currency',{min:3,max:3});v.done();if(!/^\d+$/.test(minor)||BigInt(minor)>1000000000000n||!['IRR','EUR','USD','GBP','AED'].includes(currency))throw new AppError('validation_failed');const [p]=await s.query(`insert into app.shop_product(business_id,sku,title,description,price_minor,currency) values($1,$2,$3,$4,$5::bigint,$6) returning ${COLUMNS}`,[b,sku,title,description,minor,currency]);await s.query("select app.record_audit('shop.product_created','shop_product',$1,$2::uuid),app.emit_event('shop.product_created','shop_product',$1,$2::uuid)",[p?.['id'],b]);return{status:201,body:{product:p}};}},
{method:'PUT',path:'/api/v1/shop/manage/products/:id',name:'shop.saveProduct',summary:'ویرایش نسخه‌دار؛ بدون دسترسی خام به stock/reservation',tags:['shop'],auth:'session',role:'pv_app',handler:async(r,s)=>{const b=await business(r,s,'shop.manage');await s.query('select app.require_recent_auth()');const v=validator(r.body),version=v.integer('expected_version',{min:1}),title=v.string('title',{min:2,max:200}),description=v.optionalString('description',{max:4000}),minor=v.string('price_minor',{min:1,max:13});v.done();if(!/^\d+$/.test(minor)||BigInt(minor)>1000000000000n)throw new AppError('validation_failed');const [p]=await s.query(`update app.shop_product set title=$1,description=$2,price_minor=$3::bigint where id=$4 and business_id=$5 and version=$6 returning ${COLUMNS}`,[title,description,minor,id(r.params['id']),b,version]);if(!p)throw new AppError('conflict');await s.query("select app.record_audit('shop.product_updated','shop_product',$1,$2::uuid)",[p['id'],b]);return{status:200,body:{product:p}};}},
{method:'POST',path:'/api/v1/shop/manage/products/:id/stock',name:'shop.adjustStock',summary:'تنظیم موجودی با ledger/re-auth/نسخه و حفظ رزروها',tags:['shop'],auth:'session',role:'pv_app',handler:async(r,s)=>{await business(r,s,'shop.manage');const v=validator(r.body),version=v.integer('expected_version',{min:1}),qty=v.integer('quantity',{min:0,max:100000000}),reason=v.string('reason',{min:3,max:300});v.done();const [row]=await s.query('select app.shop_adjust_stock($1,$2,$3,$4) product',[id(r.params['id']),version,qty,reason]);return{status:200,body:row??{}};}},
{method:'POST',path:'/api/v1/shop/manage/products/:id/state',name:'shop.productState',summary:'انتشار/آرشیو محصول با مجوز و audit',tags:['shop'],auth:'session',role:'pv_app',handler:async(r,s)=>{const b=await business(r,s,'shop.manage');await s.query('select app.require_recent_auth()');const v=validator(r.body),version=v.integer('expected_version',{min:1}),to=v.oneOf('to',['published','archived']);v.done();const [p]=await s.query(`update app.shop_product set status=$1 where id=$2 and business_id=$3 and version=$4 returning ${COLUMNS}`,[to,id(r.params['id']),b,version]);if(!p)throw new AppError('conflict');await s.query("select app.record_audit('shop.product_state','shop_product',$1,$2::uuid,null,$3::jsonb),app.emit_event('shop.product_published','shop_product',$1,$2::uuid)",[p['id'],b,JSON.stringify({to})]);return{status:200,body:{product:p}};}},
{method:'GET',path:'/api/v1/shop/cart',name:'shop.cart',summary:'سبد شخص و کسب‌وکار فعال؛ قیمت فقط از سرور',tags:['shop'],auth:'session',role:'pv_app',handler:async(r,s)=>{const b=await business(r,s,'shop.purchase');const [cart]=await s.query('select id,version,status from app.shop_cart where business_id=$1 and user_id=app.current_user_id() and status=\'open\'',[b]);const items=cart?await s.query('select l.product_id,l.qty,p.title,p.price_minor::text,p.currency,(p.price_minor*l.qty)::text total_minor from app.shop_cart_line l join app.shop_product p on p.id=l.product_id where l.cart_id=$1',[cart['id']]):[];return{body:{cart:cart??null,items,payment:{state:'not_configured',reason:'no payment provider configured; checkout reserves stock only'}}};}},
{method:'POST',path:'/api/v1/shop/cart',name:'shop.cartAdd',summary:'افزودن/تغییر تعداد نسخه‌دار سبد',tags:['shop'],auth:'session',role:'pv_app',handler:async(r,s)=>{await business(r,s,'shop.purchase');const v=validator(r.body),product=v.uuid('product_id'),qty=v.integer('quantity',{min:1,max:100000}),version=v.integer('expected_version',{min:0});v.done();const [row]=await s.query('select app.cart_add($1,$2,$3) cart',[product,qty,version]);return{status:200,body:row??{}};}},
{method:'POST',path:'/api/v1/shop/checkout',name:'shop.checkout',summary:'ایجاد سفارش idempotent و رزرو اتمی، بدون ادعای پرداخت',tags:['shop'],auth:'session',role:'pv_app',handler:async(r,s)=>{await business(r,s,'shop.purchase');const v=validator(r.body),cart=v.uuid('cart_id'),version=v.integer('expected_version',{min:1}),key=v.uuid('idempotency_key');v.done();const [row]=await s.query('select app.shop_checkout($1,$2,$3) "order"',[cart,version,key]);return{status:201,body:{...row,payment:{state:'not_configured',reason:'order stored and inventory reserved; no money collected'}}};}},
{method:'GET',path:'/api/v1/shop/orders',name:'shop.orders',summary:'سفارش‌های نقش فعالِ خریدار/فروشنده',tags:['shop'],auth:'session',role:'pv_app',handler:async(r,s)=>{const b=await business(r,s,r.query.get('seller')==='true'?'shop.manage':'shop.purchase');return{body:{items:await s.query('select id,business_id,seller_business_id,total_minor::text,currency,status,payment_status,version,created_at from app.shop_order where '+(r.query.get('seller')==='true'?'seller_business_id':'business_id')+'=$1 order by created_at desc,id desc limit 50',[b])}};}},
{method:'POST',path:'/api/v1/shop/orders/:id/state',name:'shop.orderState',summary:'تأیید/لغو/تحویل با edge محدود و ledger اتمی',tags:['shop'],auth:'session',role:'pv_app',handler:async(r,s)=>{if(r.auth.kind!=='session'||r.auth.activeBusinessId!==r.businessId)throw new AppError('forbidden');const v=validator(r.body),version=v.integer('expected_version',{min:1}),to=v.oneOf('to',['confirmed','cancelled','fulfilled']),reason=v.string('reason',{min:3,max:300});v.done();const [row]=await s.query('select app.shop_order_state($1,$2,$3,$4) "order"',[id(r.params['id']),version,to,reason]);return{status:200,body:row??{}};}},
];
