import {buildBusinessView,type BusinessContextRow,type ContactContextRow,type LocationContextRow} from '@petavu/design/businesscontext';
/* §32–44، §161–169: DB → Registry → renderer مشترک → اندازه‌گیری → Preview → Approval → Publish. */
import {validateValues,definitionFields,type FormSchemaView} from '@petavu/design/nocode';
import {createHash} from 'node:crypto';
import { AppError, isUuid, uuidv7 } from '@petavu/shared';
import { safeTokenValue, createRegistry, scanTree, validateProps, type RegistryRow, type TreeData, type MediaView } from '@petavu/design';
import { compilePreview, type DesignBundle, PIPELINE_STAGES } from '@petavu/design/pipeline';
import { readLocalMedia, mediaViewOf, type MediaAssetRow } from '@petavu/design/media';
import {checkThemeSettings} from '@petavu/design/themesettings';
import type { ApiRequest, Scope, RouteDefinition } from '../types.js';
import { validator } from '../validate.js';

type Json=Record<string,unknown>;
async function effective(r:ApiRequest,s:Scope,action='manage'):Promise<string|null>{const requested=r.query.get('scope');if(requested&&!['platform','business'].includes(requested))throw new AppError('validation_failed');const b=requested==='platform'?null:r.auth.kind==='session'?r.auth.activeBusinessId:null;if(requested!=='platform'&&r.businessId!==b)throw new AppError('forbidden',{details:{reason:'active_business_mismatch'}});if(r.query.get('scope')!=='platform'&&!b)throw new AppError('precondition_failed',{details:{reason:'active_business_required'}});await s.query('select design.assert_access($1::uuid,$2)',[b,action]);return b;}
const idOf=(r:ApiRequest)=>{const id=r.params['id'];if(!isUuid(id))throw new AppError('validation_failed');return id;};
async function page(r:ApiRequest,s:Scope){const b=await effective(r,s);const [p]=await s.query('select id,business_id,key,title,description,draft_title,draft_description,has_draft_metadata,draft_tree,draft_revision,version,status from design.page where id=$1::uuid and business_id is not distinct from $2::uuid',[idOf(r),b]);if(!p)throw new AppError('not_found');return p;}
async function release(r:ApiRequest,s:Scope,action='manage'){const b=await effective(r,s,action);const [p]=await s.query('select id,business_id,version,bundle,bundle_hash,status,validation_report,lock_version,source_hash,previewed_at,previewed_hash,approved_at,published_at,is_current from design.release where id=$1::uuid and business_id is not distinct from $2::uuid',[idOf(r),b]);if(!p)throw new AppError('not_found');return p;}
async function registry(s:Scope){return s.query<RegistryRow>('select key,name_fa,category,status,props_schema,slots,a11y,seo,performance from design.component where status=\'active\' order by key');}
async function vet(tree:unknown,s:Scope){const reg=createRegistry(await registry(s));const scan=scanTree(tree,{registry:reg,strings:{}});const findings=[...scan.findings];const walk=(nodes:typeof scan.nodes)=>{for(const n of nodes){const spec=reg.get(n.component);if(spec)findings.push(...validateProps(spec,n.props,n.id).findings);for(const children of Object.values(n.slots))walk(children);}};walk(scan.nodes);if(findings.some(f=>['error','blocker'].includes(f.severity)||f.rule.startsWith('security.')||f.rule.startsWith('structure.prop_')))throw new AppError('validation_failed',{details:{findings}});}
async function compile(r:ApiRequest,s:Scope,stored:Json){
 const bundle=stored['bundle'] as DesignBundle;const businessId=stored['business_id'] as string|null;
 const [b]=businessId?await s.query<BusinessContextRow>('select b.id,b.name,b.slug,b.business_type_key,t.name_fa as type_name,l.name_fa as city_name,p.tagline,p.summary from app.business b left join app.business_profile p on p.business_id=b.id left join ref.business_type t on t.key=b.business_type_key left join ref.location l on l.id=b.primary_location_id where b.id=$1',[businessId]):[];
 const reg=await registry(s);const registryObject=createRegistry(reg);const ids=[...new Set(bundle.pages.flatMap(p=>scanTree(p.tree,{registry:registryObject,strings:{}}).assetIds))];
 const assets=ids.length?await s.query<MediaAssetRow>(`select id,driver,storage_key,bucket,detected_mime,kind,size_bytes,width,height,alt_text,original_name,checksum_sha256 from media.asset where id=any(array(select jsonb_array_elements_text($1::jsonb)::uuid)) and status='ready' and is_public and deleted_at is null and (business_id is null or business_id=$2::uuid)`,[JSON.stringify(ids),businessId]):[];
 const media=new Map<string,MediaView>();const files=new Map<string,MediaAssetRow>();for(const a of assets){const v=mediaViewOf(a);if(v){media.set(a.id,v);files.set(a.id,a);}}
 const hits=await s.query('select id,slug,name,summary,city_name from app.search_businesses(null,12)');
 const contents=await s.query("select title,slug,summary,published_at from app.content where status='published' and visibility='public' and deleted_at is null and business_id is not distinct from $1::uuid order by published_at desc,id limit 12",[businessId]);
 const contacts=businessId?await s.query<ContactContextRow>('select kind,value_display,label,is_public from app.business_contact where business_id=$1 and is_public order by sort_order limit 20',[businessId]):[];
 const locations=businessId?await s.query<LocationContextRow>('select label,address_line,latitude,longitude,hours,is_primary from app.business_location where business_id=$1 order by is_primary desc,created_at limit 20',[businessId]):[];
 const data:TreeData={businesses:hits.map(v=>({name:String(v['name']),summary:v['summary'] as string|null,cityName:v['city_name'] as string|null,url:'/b/'+encodeURIComponent(String(v['slug']))})),contents:contents.map(v=>({title:String(v['title']),summary:v['summary'] as string|null,publishedAt:v['published_at']?new Date(String(v['published_at'])).toISOString():null,url:'/'+encodeURIComponent(String(v['slug']))})),business:b?buildBusinessView(b,locations,contacts,s.services.env.origins.public):null};
 const forms=new Map<string,FormSchemaView>();for(const f of bundle.definitions??[])if(f.kind==='form'&&f.spec['public']===true){const fields=definitionFields(f,bundle.definitions??[]);const [hash]=await s.query<{hash:string}>('select design.bundle_hash($1::jsonb) hash',[JSON.stringify({form:f.spec,fields})]);const view={form:f,fields,schema_hash:hash!.hash,business_id:businessId};forms.set(f.id,view);forms.set(String(f.spec['purpose']),view);}const records=new Map<string,Array<{title:string;url:string}>>();for(const def of bundle.definitions??[])if(def.kind==='crud'){const rows=await s.query(`select c.title,c.slug from app.content c join app.content_extension e on e.content_id=c.id where e.definition_id=$1 and c.business_id is not distinct from $2::uuid and c.status='published' and c.visibility='public' and c.deleted_at is null order by c.id desc limit 12`,[def.id,businessId]);records.set(def.id,rows.map(v=>({title:String(v['title']),url:businessId?'/b/'+encodeURIComponent(String(b?.slug))+'/c/'+encodeURIComponent(String(v['slug'])):'/'+encodeURIComponent(String(v['slug']))})));}
 const [site]=await s.query<{name:string}>('select name_fa as name from seo.entity where is_brand_anchor order by created_at limit 1');
 const strings={site_name:site?.name??'PETAVU',business_name:String(b?.['name']??site?.name??'PETAVU'),tagline:String(b?.['tagline']??''),summary:String(b?.['summary']??''),type_name:String(b?.type_name??''),business_type:String(b?.type_name??'پلتفرم'),city:String(b?.city_name??''),business_count:String(hits.length),content_count:String(contents.length)};
 const preview=await compilePreview({bundle,registry:reg,origin:s.services.env.origins.public,businessSlug:b?String(b['slug']):null,data:{...data,forms,records},strings,media,fetchMedia:async(id)=>{const asset=files.get(id);if(!asset||asset.driver!=='local')return {status:404,contentType:'application/octet-stream',bytes:Buffer.alloc(0)};const file=await readLocalMedia(s.services.env.storage.localDir,asset.storage_key,{contentType:asset.detected_mime});return file&&asset.checksum_sha256===createHash('sha256').update(file.body).digest('hex')?{status:200,contentType:asset.detected_mime,bytes:file.body}:{status:404,contentType:asset.detected_mime,bytes:Buffer.alloc(0)};}});
 void r;return preview;
}
interface Check {stage:string;status:'passed'|'failed'|'not_applicable'|'pending';evidence:unknown}
async function evaluate(r:ApiRequest,s:Scope,stored:Json){const output=await compile(r,s,stored);const bundle=stored['bundle'] as DesignBundle;const all=[...output.tokenFindings,...output.pages.flatMap(p=>p.findings)];
 const dbFindings=[];for(const p of bundle.pages){const [row]=await s.query<{findings:unknown[]}>('select design.validate_tree($1::jsonb) as findings',[JSON.stringify(p.tree)]);dbFindings.push(...(row?.findings??[]));}
 const budgets=[];for(const p of output.pages){const [row]=await s.query<{budget:Json}>('select ops.check_budget($1,$2::jsonb) as budget',[p.path,JSON.stringify(p.delivery.measurement)]);budgets.push({path:p.path,measurement:p.delivery.measurement,resources:p.delivery.resources,failed:p.delivery.failed,budget:row?.budget});}
 const [gate]=await s.query<{gate:Json}>('select ops.publish_gate($1::uuid) as gate',[stored['business_id']??null]);
 const [regressions]=await s.query<{n:number}>("select count(*)::int n from ops.performance_regression where status='open' and severity='critical'");
 const stages:Check[]=[];const add=(stage:string,pass:boolean,evidence:unknown)=>stages.push({stage,status:pass?'passed':'failed',evidence});
 add('CHANGE',bundle.pages.length>0,{hash:stored['bundle_hash'],pages:bundle.pages.length});
 add('VALIDATE',!dbFindings.length&&!all.some(v=>v.severity==='error'||v.severity==='blocker'),{findings:[...dbFindings,...all]});
 add('SECURITY',!all.some(v=>v.rule.startsWith('security.')),{findings:all.filter(v=>v.rule.startsWith('security.')),renderer:'registry_only_no_raw_code'});
 const impact=[];for(const model of bundle.definitions??[])if(model.kind==='crud'&&model.business_id===stored['business_id']){const fields=definitionFields(model,bundle.definitions??[]);const rows=await s.query('select e.content_id,e.values from app.content_extension e join app.content c on c.id=e.content_id where e.definition_id=$1 and e.business_id is not distinct from $2::uuid and c.deleted_at is null limit 1001',[model.id,stored['business_id']??null]);if(rows.length>1000)impact.push({model:model.id,reason:'requires_bounded_backfill_before_publish'});for(const row of rows.slice(0,1000))try{validateValues(fields,row['values'] as Json);}catch{impact.push({id:row['content_id'],reason:'existing_record_invalid_for_new_schema'});}}if(impact.length){all.push(...impact.map(v=>({rule:'nocode.schema_impact',severity:'blocker' as const,message:JSON.stringify(v)})));const validated=stages.find(c=>c.stage==='VALIDATE');if(validated){validated.status='failed';validated.evidence={findings:all,impact};}}
 add('DB',true,{scope:stored['business_id']??'platform',source_hash:stored['source_hash'],pages:bundle.pages.map(p=>({id:p.id,version:p.version}))});
 add('API',studioRoutes.every(v=>v.auth==='session'),{contracts:studioRoutes.map(v=>({method:v.method,path:v.path,auth:v.auth}))});
 add('PERFORMANCE',budgets.every(v=>v.budget?.['verdict']==='pass'&&!v.failed.length)&&['pass','allow'].includes(String(gate?.gate['verdict']))&&!regressions?.n,{delivery:budgets,existing_gate:gate?.gate,critical_regressions:regressions?.n??0,cwv:'not_compared_without_browser_samples'});
 add('A11Y',!all.some(v=>v.rule.startsWith('a11y.')),{findings:all.filter(v=>v.rule.startsWith('a11y.')),headings:output.pages.map(p=>({path:p.path,h1:p.h1Count,outline:p.outline})),strategy:'semantic_static_checks',browser_box_metrics:'requires_browser_quality_suite',css:output.pages.map(p=>({path:p.path,has_44px_controls:/min-block-size:\s*(?:44px|var\(--size-touch-target,\s*44px\))/.test(p.css),has_reduced_motion:/prefers-reduced-motion:\s*reduce/.test(p.css)}))});
 add('SEO',!all.some(v=>v.rule.startsWith('seo.')),{pages:bundle.pages.map(p=>{const rendered=output.pages.find(v=>v.id===p.id)!;const characters=rendered.fragment.replace(/<[^>]*>/g,'').trim().length;return {id:p.id,title:p.title,description:p.description,body_characters:characters,indexable:characters>=80};}),preview_indexing:false});
 add('SD',output.pages.every(p=>p.html.includes('application/ld+json')),{graphs:output.pages.map(p=>({path:p.path,graph:JSON.parse(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/.exec(p.html)?.[1]??'{}')}))});
 add('SEARCH',true,{document_scope:stored['business_id']??'platform',documents:bundle.pages.map(p=>({id:p.id,title:p.title})),update_event:'design.published'});
 add('SITEMAP',output.pages.every(p=>p.path.startsWith('/')&&!p.path.includes('?')),{paths:output.pages.map(p=>p.path),private_and_noindex_excluded:true,update_event:'design.published'});
 add('AI',true,{source:'rendered_page_only',paths:output.pages.map(p=>p.path),robots:'environment_aware'});
 const [functions]=await s.query<{event:boolean;automation:boolean}>("select to_regprocedure('app.emit_event(text,text,text,uuid,jsonb,text)') is not null as event,to_regprocedure('ops.process_event(uuid)') is not null as automation");
 add('AUTOMATION',functions?.event===true&&functions?.automation===true,{functions,outbox_event:'design.published'});
 for(const stage of PIPELINE_STAGES.slice(13))stages.push({stage,status:stage==='PREVIEW'&&stored['previewed_hash']===stored['bundle_hash']?'passed':'pending',evidence:stage==='PREVIEW'&&stored['previewed_hash']===stored['bundle_hash']?{hash:stored['previewed_hash'],viewed_at:stored['previewed_at']}:'requires_actual_workflow_action'});
 for(const f of all) await s.query('insert into design.audit(business_id,release_id,check_kind,severity,rule_key,message,path) values($1::uuid,$2::uuid,$3,$4,$5,$6,$7)',[stored['business_id']??null,stored['id'],f.rule.startsWith('security.')?'security':f.rule.startsWith('a11y.')?'a11y':'structure',f.severity,f.rule,f.message,f.path??null]);
 return {report:{checks:stages,measured_at:new Date(s.services.now()).toISOString(),findings:all},output};
}
const route=(method:RouteDefinition['method'],path:string,name:string,summary:string,handler:RouteDefinition['handler']):RouteDefinition=>({method,path:'/api/v1/studio'+path,name:'studio.'+name,summary,tags:['design'],auth:'session',role:'pv_app',handler});
export const studioRoutes:RouteDefinition[]=[
 route('GET','', 'overview','استودیو: scope=platform یا کسب‌وکار فعال، با مجوز DB',async(r,s)=>{const b=await effective(r,s);const pages=await s.query('select id,key,title,description,status,draft_title,draft_description,has_draft_metadata,draft_revision,published_release_id,version from design.page where business_id is not distinct from $1::uuid order by key limit 100',[b]);const [tokenRows]=await s.query<{items:Json[]}>('select design.studio_tokens($1::uuid) as items',[b]);const tokens=tokenRows?.items??[];const themes=await s.query('select id,key,name_fa,settings,draft_settings,is_default,version from design.theme where business_id is not distinct from $1::uuid order by key',[b]);const releases=await s.query('select id,version,lock_version,status,bundle_hash,previewed_at,approved_at,published_at,is_current,created_at from design.release where business_id is not distinct from $1::uuid order by version desc limit 30',[b]);return {body:{scope:b,pages,tokens,themes,releases,components:await registry(s),stages:PIPELINE_STAGES}};}),
 route('POST','/pages','createPage','صفحهٔ جدید؛ فقط درخت Registry',async(r,s)=>{const b=await effective(r,s);const v=validator(r.body);const key=v.string('key',{min:2,max:60});const title=v.string('title',{min:2,max:200});const tree=v.raw('tree')??{version:1,root:[]};v.done();if(!/^[a-z][a-z0-9_-]*$/.test(key))throw new AppError('validation_failed');await vet(tree,s);const [p]=await s.query("insert into design.page(business_id,key,title,scope,is_system,draft_tree) values($1,$2,$3,$4,$5,$6::jsonb) returning id,key,title,version,draft_tree",[b,key,title,b?'business':'platform',!b,JSON.stringify(tree)]);await s.query("select app.record_audit('design.page_created','design_page',$1,$2::uuid)",[p?.['id'],b]);return {status:201,body:{page:p}};}),
 route('GET','/pages/:id','page','پیش‌نویس یک صفحه، در محدودهٔ فعال',async(r,s)=>({body:{page:await page(r,s)}})),
 route('PUT','/pages/:id','savePage','ذخیرهٔ نسخه‌دار با بازرسی بازگشتی',async(r,s)=>{const p=await page(r,s);const b=validator(r.body);const version=b.integer('expected_version',{min:1});const tree=b.raw('tree');const summary=b.optionalString('change_summary',{max:300});b.done();await vet(tree,s);const [result]=await s.query('select design.save_page($1::uuid,$2,$3::jsonb,$4) as page',[p['id'],version,JSON.stringify(tree),summary]);return {status:200,body:{page:result?.['page']}};}),
 route('PUT','/pages/:id/metadata','pageMetadata','پیش‌نویس متادیتای صفحه',async(r,s)=>{const p=await page(r,s),v=validator(r.body),version=v.integer('expected_version',{min:1}),title=v.string('title',{min:3,max:200}),description=v.optionalString('description',{max:400});v.done();const [updated]=await s.query('update design.page set draft_title=$1,draft_description=$2,has_draft_metadata=true where id=$3 and version=$4 returning id,version',[title,description,p['id'],version]);if(!updated)throw new AppError('conflict');return{status:200,body:{page:updated}};}),
 route('GET','/pages/:id/revisions','revisions','نسخه‌های تغییرناپذیر',async(r,s)=>{const p=await page(r,s);return {body:{items:await s.query('select id,revision,tree,tree_hash,change_summary,created_at from design.page_revision where page_id=$1 order by revision desc limit 30',[p['id']])}};}),
 route('POST','/pages/:id/restore','restoreDraft','بازگردانی نسخه به پیش‌نویس، نه انتشار',async(r,s)=>{const p=await page(r,s);const b=validator(r.body);const version=b.integer('expected_version',{min:1});const revision=b.integer('revision',{min:1});b.done();const [old]=await s.query('select tree from design.page_revision where page_id=$1 and revision=$2',[p['id'],revision]);if(!old)throw new AppError('not_found');const [result]=await s.query('select design.save_page($1::uuid,$2,$3::jsonb,$4) as page',[p['id'],version,JSON.stringify(old['tree']),`restore:${revision}`]);return {status:200,body:{page:result?.['page']}};}),
 route('POST','/tokens/:id/override','overrideToken','ساخت Draft توکنِ مختص کسب‌وکار',async(r,s)=>{const b=await effective(r,s);const [result]=await s.query('select design.override_token($1::uuid,$2::uuid) as token',[idOf(r),b]);return{status:201,body:{token:result?.['token']}};}),
 route('PUT','/tokens/:id','saveToken','مقدار توکن فقط به Draft می‌رود',async(r,s)=>{const scope=await effective(r,s);const [token]=await s.query('select id,key,value_type,business_id from design.token where id=$1::uuid and business_id is not distinct from $2::uuid',[idOf(r),scope]);if(!token)throw new AppError('not_found');const b=validator(r.body);const version=b.integer('expected_version',{min:1});const value=b.raw('value');const alias=b.optionalString('alias_of',{max:120});b.done();if(alias&&!/^[a-z][a-z0-9_]*(\.[a-z0-9_]+)+$/.test(alias))throw new AppError('validation_failed');try{safeTokenValue(String(token['key']),token['value_type'] as Parameters<typeof safeTokenValue>[1],value);}catch{throw new AppError('validation_failed');}const [updated]=await s.query('update design.token set draft_value=$1::jsonb,draft_alias_of=$2,has_draft=true where id=$3 and version=$4 returning id,key,draft_value,version',[JSON.stringify(value),alias,token['id'],version]);if(!updated)throw new AppError('conflict');await s.query("select app.record_audit('design.token_drafted','design_token',$1,$2::uuid)",[token['id'],scope]);return {status:200,body:{token:updated}};}),
 route('PUT','/themes/:id','saveTheme','پیش‌نویس نسخه‌دار تم',async(r,s)=>{const scope=await effective(r,s);const b=validator(r.body);const version=b.integer('expected_version',{min:1});const settings=b.object('settings');b.done();if(checkThemeSettings(settings).length)throw new AppError('validation_failed');const [item]=await s.query('update design.theme set draft_settings=$1::jsonb where id=$2::uuid and business_id is not distinct from $3::uuid and version=$4 returning id,key,draft_settings,version',[JSON.stringify(settings),idOf(r),scope,version]);if(!item)throw new AppError('conflict');return {status:200,body:{theme:item}};}),
 route('POST','/releases','prepare','تهیهٔ Snapshot تغییرناپذیر',async(r,s)=>{const b=await effective(r,s);const [result]=await s.query('select design.create_release($1::uuid) as id',[b]);return {status:201,body:{id:result?.['id']}};}),
 route('GET','/releases/:id','release','بسته و گواه انتشار',async(r,s)=>({body:{release:await release(r,s)}})),
 route('POST','/releases/:id/validate','validate','اجرای بازرسی واقعی و بودجهٔ اندازه‌گیری‌شده',async(r,s)=>{const stored=await release(r,s);const result=await evaluate(r,s,stored);const [updated]=await s.query('select design.record_validation($1::uuid,$2::jsonb) as release',[stored['id'],JSON.stringify(result.report)]);return {status:200,body:{release:updated?.['release'],report:result.report}};}),
 route('POST','/releases/:id/preview','preview','رندر پیش‌نمایش و ثبت مشاهدهٔ همان hash',async(r,s)=>{const stored=await release(r,s);const output=await compile(r,s,stored);const b=validator(r.body);const pageKey=b.optionalString('page_key',{max:60});b.done();const index=pageKey?(stored['bundle'] as DesignBundle).pages.findIndex(p=>p.key===pageKey):0;const preview=output.pages[index];if(!preview)throw new AppError('not_found');const [updated]=await s.query('select design.mark_preview($1::uuid,$2) as release',[stored['id'],stored['bundle_hash']]);return {status:200,body:{release:updated?.['release'],preview:{html:preview.fragment,document:preview.html,css:preview.css,path:preview.path,delivery:preview.delivery},token_findings:output.tokenFindings}};}),
 route('POST','/releases/:id/approve','approve','تأیید تنها پس از Preview/Validation و re-auth',async(r,s)=>{const stored=await release(r,s,'publish');const b=validator(r.body);const lock=b.integer('expected_version',{min:1});b.done();const [result]=await s.query('select design.approve_release($1::uuid,$2) as release',[stored['id'],lock]);return {status:200,body:{release:result?.['release']}};}),
 route('POST','/releases/:id/publish','publish','انتشار اتمی Snapshot تأییدشده',async(r,s)=>{const stored=await release(r,s,'publish');const b=validator(r.body);const lock=b.integer('expected_version',{min:1});b.done();const [gate]=await s.query<{gate:Json}>('select ops.publish_gate($1::uuid) as gate',[stored['business_id']??null]);if(!['pass','allow'].includes(String(gate?.gate['verdict'])))throw new AppError('precondition_failed',{details:{gate:gate?.gate}});const checks=(stored['validation_report'] as Json)['checks'] as Json[];const performance=checks?.find(v=>v['stage']==='PERFORMANCE')?.['evidence'] as Json|undefined;for(const p of (performance?.['delivery']??[]) as Json[]){const [current]=await s.query<{budget:Json}>('select ops.check_budget($1,$2::jsonb) as budget',[p['path'],JSON.stringify(p['measurement'])]);if(current?.budget['verdict']!=='pass')throw new AppError('precondition_failed',{details:{budget:current?.budget}});}const [result]=await s.query('select design.activate_release($1::uuid,$2,false) as release',[stored['id'],lock]);return {status:200,body:{release:result?.['release']}};}),
 route('POST','/releases/:id/rollback','rollback','بازگشت دقیق به Snapshot قبلاً منتشرشده',async(r,s)=>{const stored=await release(r,s,'rollback');const b=validator(r.body);const lock=b.integer('expected_version',{min:1});b.done();const [result]=await s.query('select design.activate_release($1::uuid,$2,true) as release',[stored['id'],lock]);return {status:200,body:{release:result?.['release']}};}),
 route('GET','/compare','compare','مقایسهٔ بسته‌ها در همان محدوده',async(r,s)=>{const scope=await effective(r,s);const from=r.query.get('from'),to=r.query.get('to');if(!isUuid(from)||!isUuid(to))throw new AppError('validation_failed');const items=await s.query('select id,bundle,bundle_hash from design.release where id in ($1::uuid,$2::uuid) and business_id is not distinct from $3::uuid',[from,to,scope]);if(items.length!==2)throw new AppError('not_found');const a=items.find(v=>v['id']===from),b=items.find(v=>v['id']===to);return {body:{from,to,from_hash:a?.['bundle_hash'],to_hash:b?.['bundle_hash'],before:a?.['bundle'],after:b?.['bundle']}};}),
];

// Builder، دادهٔ عمل را می‌گیرد؛ تغییر AST در سرور انجام می‌شود و همان بازرسی/نسخه را دارد.
for(const action of ['add','patch','remove'] as const) studioRoutes.push(route(action==='patch'?'PATCH':action==='remove'?'DELETE':'POST',`/pages/:id/nodes${action==='add'?'':'/:nodeId'}`,`node${action}`,'ویرایش محدود گرهٔ Registry در سرور',async(r,s)=>{
 const p=await page(r,s),v=validator(r.body),version=v.integer('expected_version',{min:1}),tree=structuredClone(p['draft_tree']) as {version:number;root:Array<Json>};
 const props=action==='remove'?{}:v.optionalObject('props')??{};const component=action==='add'?v.string('component',{min:3,max:80}):null;const parent=action==='add'?v.optionalString('parent_id',{max:60}):null;const slot=action==='add'?v.optionalString('slot',{max:60})??'children':null;v.done();if(slot&&(!/^[a-z][a-z0-9_]{0,59}$/.test(slot)||['__proto__','constructor','prototype'].includes(slot)))throw new AppError('validation_failed');
 let found=false;const walk=(nodes:Json[])=>{for(let i=0;i<nodes.length;i++){const n=nodes[i]!;if(n['id']===(action==='add'?parent:r.params['nodeId'])){found=true;if(action==='remove'){nodes.splice(i,1);return;}if(action==='patch')n['props']=props;else{const slots=(n['slots']??{}) as Record<string,Json[]>;slots[slot!]=[...(slots[slot!]??[]),{id:uuidv7(),component,props}];n['slots']=slots;}return;}for(const child of Object.values((n['slots']??{}) as Record<string,Json[]>))if(Array.isArray(child))walk(child);}};
 if(action==='add'&&!parent){tree.root.push({id:uuidv7(),component,props});found=true;}else walk(tree.root);if(!found)throw new AppError('not_found');await vet(tree,s);
 const [result]=await s.query('select design.save_page($1::uuid,$2,$3::jsonb,$4) as page',[p['id'],version,JSON.stringify(tree),`builder:${action}`]);return{status:200,body:{page:result?.['page']}};
}));
