/* Addendum §73–80: DSL داده‌ای محدود؛ نه SQL، نه expression evaluator، نه کد کلاینت. */
import {AppError,isUuid,normalizePersian} from '@petavu/shared';
export const FIELD_TYPES=['text','longtext','number','boolean','date','email','phone','url','enum','reference','asset'] as const;
export type FieldType=typeof FIELD_TYPES[number];
export type DefinitionKind='field'|'relationship'|'form'|'crud';
export interface Definition {id:string;business_id:string|null;key:string;kind:DefinitionKind;spec:Record<string,unknown>;version:number}
export interface FieldSpec {type:FieldType;label_fa:string;label_en?:string;required?:boolean;public?:boolean;sensitive?:boolean;min?:number;max?:number;max_length?:number;options?:Array<{key:string;label_fa:string;label_en?:string}>;reference_model?:string;read_permission?:string}
const KEY=/^[a-z][a-z0-9_]{1,59}$/;
const forbidden=new Set(['__proto__','constructor','prototype','sql','js','javascript','script','code','html','css','expression','regex','server_code']);
function bad(reason:string):never{throw new AppError('validation_failed',{details:{reason}});}
function inspect(value:unknown,depth=0):void{if(depth>8)bad('definition_depth');if(Array.isArray(value)){if(value.length>50)bad('definition_array_limit');for(const v of value)inspect(v,depth+1);}else if(value&&typeof value==='object'){for(const[k,v]of Object.entries(value)){if(forbidden.has(k.toLowerCase()))bad('no_code_boundary');inspect(v,depth+1);}}else if(typeof value==='string'&&value.length>4000)bad('definition_string_limit');}
function keys(value:Record<string,unknown>,allowed:readonly string[]):void{if(Object.keys(value).some(k=>!allowed.includes(k)))bad('unknown_definition_property');}
function text(value:unknown,min=1,max=200):string{if(typeof value!=='string'||value.trim().length<min||value.length>max)bad('definition_text');return value;}
function ids(value:unknown):string[]{if(!Array.isArray(value)||value.length===0||value.length>30||value.some(v=>!isUuid(v))||new Set(value).size!==value.length)bad('definition_field_ids');return value as string[];}
export function validateDefinition(kind:DefinitionKind,spec:Record<string,unknown>):void{inspect(spec);if(kind==='field'){keys(spec,['type','label_fa','label_en','required','public','sensitive','min','max','max_length','options','reference_model','read_permission']);if(!FIELD_TYPES.includes(spec['type'] as FieldType))bad('field_type');text(spec['label_fa']);if(spec['label_en']!==undefined)text(spec['label_en']);for(const k of ['required','public','sensitive'])if(spec[k]!==undefined&&typeof spec[k]!=='boolean')bad('field_flag');if(spec['sensitive']===true&&spec['public']===true)bad('private_field_cannot_be_public');for(const k of ['min','max','max_length'])if(spec[k]!==undefined&&(typeof spec[k]!=='number'||!Number.isFinite(spec[k])))bad('field_bound');if(typeof spec['min']==='number'&&typeof spec['max']==='number'&&spec['min']>spec['max'])bad('field_bounds');if(spec['max_length']!==undefined&&(!Number.isInteger(spec['max_length'])||Number(spec['max_length'])<1||Number(spec['max_length'])>4000))bad('field_max_length');if(spec['type']==='enum'){const options=spec['options'];if(!Array.isArray(options)||options.length<1||options.length>50)bad('enum_options');const seen=new Set<string>();for(const raw of options){if(!raw||typeof raw!=='object'||Array.isArray(raw))bad('enum_option');const o=raw as Record<string,unknown>;keys(o,['key','label_fa','label_en']);const key=text(o['key'],1,60);if(!/^[a-z0-9][a-z0-9_-]{0,59}$/.test(key)||seen.has(key))bad('enum_key');seen.add(key);text(o['label_fa']);if(o['label_en']!==undefined)text(o['label_en']);}}if(spec['type']==='reference'&&!isUuid(spec['reference_model']))bad('reference_model');if(spec['read_permission']!==undefined&&!/^\w+\.\w+(?:\.\w+)?$/.test(String(spec['read_permission'])))bad('field_permission');}
 else if(kind==='form'){keys(spec,['title_fa','title_en','field_ids','purpose','public','consent_required','success_message','submit_label']);text(spec['title_fa']);ids(spec['field_ids']);if(!['contact','lead','newsletter','custom'].includes(String(spec['purpose'])))bad('form_purpose');if(spec['public']!==undefined&&typeof spec['public']!=='boolean')bad('form_public');if(spec['consent_required']!==true)bad('form_consent_required');if(spec['success_message']!==undefined)text(spec['success_message'],1,300);}
 else if(kind==='crud'){keys(spec,['title_fa','title_en','field_ids','content_kind','title_field','summary_field','search_fields']);text(spec['title_fa']);ids(spec['field_ids']);if(!['page','article','service','listing'].includes(String(spec['content_kind'])))bad('crud_target_not_allowed');if(!KEY.test(String(spec['title_field'])))bad('crud_title_field');if(spec['summary_field']!==undefined&&!KEY.test(String(spec['summary_field'])))bad('crud_summary_field');if(spec['search_fields']!==undefined&&(!Array.isArray(spec['search_fields'])||(spec['search_fields'] as unknown[]).some(v=>!KEY.test(String(v)))))bad('crud_search_fields');}
 else if(kind==='relationship'){keys(spec,['label_fa','label_en','relationship_kind','symmetric']);text(spec['label_fa']);if(!['partner','supplier','customer','parent','branch_of','affiliate'].includes(String(spec['relationship_kind'])))bad('relationship_kind');if(spec['symmetric']!==undefined&&typeof spec['symmetric']!=='boolean')bad('relationship_symmetric');}
 else bad('definition_kind');}
export function definitionFields(def:Definition,definitions:readonly Definition[]):Definition[]{const fields=ids(def.spec['field_ids']).map(id=>definitions.find(v=>v.id===id&&v.kind==='field'));if(fields.some(v=>!v))bad('missing_field_definition');if(new Set((fields as Definition[]).map(f=>f.key)).size!==fields.length)bad('duplicate_field_key');return fields as Definition[];}
export function validateValues(fields:readonly Definition[],values:Record<string,unknown>,coerce=false):Record<string,unknown>{if(Object.keys(values).some(k=>!fields.some(f=>f.key===k)))bad('unknown_field');const out:Record<string,unknown>=Object.create(null) as Record<string,unknown>;for(const f of fields){const s=f.spec as unknown as FieldSpec;let v=values[f.key];if(v===undefined||v===null||v===''){if(s.required)bad('required:'+f.key);continue;}if(coerce&&typeof v==='string'&&['number','boolean','date','phone'].includes(s.type)){v=normalizePersian(v);if(s.type==='number'&&/^-?\d+(?:\.\d+)?$/.test(v as string))v=Number(v);else if(s.type==='boolean'){if(!['true','false','1','0','on','off'].includes(v as string))bad('boolean:'+f.key);v=['true','1','on'].includes(v as string);}}
 if(s.type==='number'){if(typeof v!=='number'||!Number.isFinite(v)||(s.min!==undefined&&v<s.min)||(s.max!==undefined&&v>s.max))bad('number:'+f.key);}else if(s.type==='boolean'){if(typeof v!=='boolean')bad('boolean:'+f.key);}else{if(typeof v!=='string'||v.length>(s.max_length??4000)||v.includes('\u0000'))bad('text:'+f.key);const value=v as string;if(s.type==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))bad('email:'+f.key);if(s.type==='phone'&&!/^\+?[0-9 ()-]{6,30}$/.test(value))bad('phone:'+f.key);if(s.type==='url'){try{const url=new URL(value);if(!['https:','http:'].includes(url.protocol))bad('url:'+f.key);}catch{bad('url:'+f.key);}}if(s.type==='date'&&(!/^\d{4}-\d{2}-\d{2}$/.test(value)||!Number.isFinite(Date.parse(value+'T00:00:00Z'))||new Date(value+'T00:00:00Z').toISOString().slice(0,10)!==value))bad('date:'+f.key);if(s.type==='enum'&&!s.options?.some(o=>o.key===value))bad('enum:'+f.key);if(['reference','asset'].includes(s.type)&&!isUuid(value))bad('reference:'+f.key);}
 out[f.key]=v;}
 return out;}
export function publicProjection(fields:readonly Definition[],values:Record<string,unknown>):{blocks:Array<{kind:'paragraph';text:string}>;text:string}{const blocks=fields.filter(f=>f.spec['public']===true&&f.spec['sensitive']!==true&&values[f.key]!==undefined).map(f=>({kind:'paragraph' as const,text:String(f.spec['label_fa'])+': '+String(values[f.key])}));return{blocks,text:blocks.map(b=>b.text).join('\n')};}
export function definitionFindings(definitions:readonly Definition[]):Array<{rule:string;severity:'blocker';message:string}>{const findings:Array<{rule:string;severity:'blocker';message:string}>=[];for(const d of definitions)try{validateDefinition(d.kind,d.spec);if(d.kind==='form'||d.kind==='crud'){const fields=definitionFields(d,definitions);if(d.kind==='crud')for(const key of [d.spec['title_field'],d.spec['summary_field'],...((d.spec['search_fields']??[]) as unknown[])].filter(v=>v!==undefined))if(!fields.some(f=>f.key===key&&f.spec['public']===true&&f.spec['sensitive']!==true))bad('projection_fields_must_be_public');}}catch(error){findings.push({rule:'nocode.definition',severity:'blocker',message:d.key+': '+(error instanceof Error?error.message:'invalid')});}return findings;}

export interface FormSchemaView {form:Definition;fields:Definition[];schema_hash:string;business_id:string|null}
