import {createPostgresClient} from '../packages/db/dist/index.js';import {mkdir,writeFile} from 'node:fs/promises';
const url=process.env.DATABASE_URL??process.env.PETAVU_DATABASE_URL;if(!url)throw new Error('DATABASE_URL required; native concurrency is not emulated');const c=await createPostgresClient({url,poolMax:6,statementTimeoutMs:15000});const record={at:new Date().toISOString()};
async function actor(user,business,session,fn){return c.withTransaction(tx=>tx.asRole('pv_app',async client=>{await client.query("select set_config('app.user_id',$1,true),set_config('app.business_id',$2,true),set_config('app.session_id',$3,true)",[user,business,session]);return fn(client);}));}
try{
 record.engine=(await c.query('select version() v')).rows[0].v;
 const users=(await c.query("insert into auth.app_user(display_name,status) values('Native seller QA','active'),('Native buyer A QA','active'),('Native buyer B QA','active') returning id")).rows;
 const type=(await c.query('select key from ref.business_type order by key limit 1')).rows[0].key;const nonce=Date.now().toString();const businesses=[];const sessions=[];
 for(let i=0;i<3;i++){const b=(await c.query("insert into app.business(name,slug,business_type_key,owner_user_id,status,visibility) values($1,$2,$3,$4,'active','public') returning id",['Native QA '+i,'native-'+nonce+'-'+i,type,users[i].id])).rows[0].id;businesses.push(b);const role=(await c.query("select id from app.role where business_id is null and key='owner'")).rows[0].id;await c.query("insert into app.membership(business_id,user_id,role_id,status,joined_at) values($1,$2,$3,'active',now())",[b,users[i].id,role]);const s=(await c.query("insert into auth.session(user_id,secret_hash,aal,step_up_at,expires_at,absolute_expires_at) values($1,$2,1,now(),now()+interval '1 hour',now()+interval '1 hour') returning id",[users[i].id,crypto.randomUUID().replace(/-/g,'')+crypto.randomUUID().replace(/-/g,'')])).rows[0].id;sessions.push(s);}
 const product=(await c.query("insert into app.shop_product(business_id,sku,title,price_minor,currency,stock_qty,status) values($1,$2,'Native atomic inventory',1250,'EUR',1,'published') returning id",[businesses[0],'NATIVE-'+nonce])).rows[0].id;
 const carts=[];for(let i=1;i<=2;i++)carts.push(await actor(users[i].id,businesses[i],sessions[i],async tx=>(await tx.query('select app.cart_add($1,1,0) cart',[product])).rows[0].cart));
 const results=await Promise.allSettled([1,2].map((i)=>actor(users[i].id,businesses[i],sessions[i],async tx=>(await tx.query('select app.shop_checkout($1,$2,$3) result',[carts[i-1].id,carts[i-1].version,crypto.randomUUID()])).rows[0].result)));
 const row=(await c.query('select stock_qty,reserved_qty from app.shop_product where id=$1',[product])).rows[0];record.concurrent_inventory={successes:results.filter(r=>r.status==='fulfilled').length,failures:results.filter(r=>r.status==='rejected').length,stock:row};if(record.concurrent_inventory.successes!==1||row.reserved_qty!==1)throw new Error('native oversell protection failed');
 const contexts=await Promise.all([1,2].map(i=>actor(users[i].id,businesses[i],sessions[i],async tx=>(await tx.query('select app.current_user_id() uid,app.current_business_id() bid')).rows[0])));if(contexts[0].uid===contexts[1].uid||contexts.some((x,i)=>x.bid!==businesses[i+1]))throw new Error('pooled context leaked');record.context_isolation=true;
 const p=(await c.query('select current_setting(\'server_version\') version')).rows[0];record.server_version=p.version;record.passed=true;await mkdir('quality/evidence',{recursive:true});await writeFile('quality/evidence/native.json',JSON.stringify(record,null,2));console.log(JSON.stringify(record,null,2));
}finally{await c.close();}
