import {useEffect,useState} from 'react';
import {ArrowUpLeft,ArrowDown,Pause,Play,Copy,Check,ShieldCheck,Store,Stethoscope,Warehouse,Truck,Boxes,Factory,PackageOpen,GraduationCap,HeartHandshake,Orbit} from 'lucide-react';
import Brand from './Brand';
import ScrollExperience from './ScrollExperience';
import './launch.css';
const groups=[{name:'پت‌شاپ‌ها',icon:Store},{name:'دامپزشکان و مراکز درمانی',icon:Stethoscope},{name:'اسطبل‌ها و مراکز اسب',icon:Warehouse},{name:'تأمین‌کنندگان و پخش‌کنندگان',icon:Truck},{name:'عمده‌فروشان',icon:Boxes},{name:'تولیدکنندگان',icon:Factory},{name:'واردکنندگان',icon:PackageOpen},{name:'آموزش و خدمات تخصصی',icon:GraduationCap}];
export default function PublicLaunch(){
 const[motion,setMotion]=useState(()=>!matchMedia('(prefers-reduced-motion: reduce)').matches);const[copied,setCopied]=useState(false);const[showLink,setShowLink]=useState(false);
 useEffect(()=>{document.documentElement.dataset.motion=motion?'on':'off'},[motion]);
 useEffect(()=>{const mq=matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setMotion(!mq.matches);mq.addEventListener('change',update);return()=>mq.removeEventListener('change',update)},[]);
 function currentPublicUrl(){if(!location.protocol.startsWith('http'))return '';const url=new URL(location.href);url.hash='';url.search='';url.pathname=url.pathname.replace(/index\.html$/,'');return url.href}
 async function copyLink(){const url=currentPublicUrl();if(!url){setShowLink(true);return}try{await navigator.clipboard.writeText(url);setCopied(true);setTimeout(()=>setCopied(false),3500)}catch{setShowLink(true)}}
 return <div className="public-launch"><a className="skip-link" href="#main">رفتن به محتوای اصلی</a><header className="launch-header"><div className="launch-container launch-navigation"><a href="#story" className="brand-link" aria-label="پِتاو، آغاز داستان"><Brand/></a><nav aria-label="ناوبری صفحهٔ عمومی"><a href="#launch-info">پِتاو در راه است <ArrowUpLeft size={16}/></a><span className="launch-status"><span/> به‌زودی</span><button className="launch-icon-btn" onClick={()=>setMotion(!motion)} aria-pressed={motion} aria-label={motion?'توقف حرکت‌های تزئینی':'فعال‌کردن حرکت‌های تزئینی'}>{motion?<Pause size={17}/>:<Play size={17}/>}</button></nav></div></header><main id="main"><ScrollExperience motion={motion} publicOnly/>
 <section id="launch-info" className="launch-info launch-container"><div className="launch-section-kicker"><span/> یک شبکهٔ تازه، برای یک دنیای مشترک</div><div className="launch-announcement"><div><h2>پِتاو در راه است.<br/><span>همکاری‌های بهتر، از اینجا شروع می‌شوند.</span></h2><p>در حال ساخت یک فضای حرفه‌ای برای ارتباط میان کسب‌وکارهای صنعت پت و اسب هستیم؛ از تولید و تأمین تا مراقبت و آموزش.</p><p className="launch-no-date">زمان راه‌اندازی و مسیر عضویت، پس از آماده شدن سرویس‌ها اعلام می‌شود.</p></div><div className="launch-seal"><Orbit size={43} strokeWidth={1.1}/><strong lang="en" dir="ltr">PETAVU</strong><span>یک حلقهٔ حرفه‌ای.</span></div></div>
 <div className="launch-group-title"><h3>برای آن‌ها که حرفه‌ای همکاری می‌کنند.</h3><span><HeartHandshake size={17}/> ارتباط کسب‌وکار با کسب‌وکار</span></div><div className="launch-groups">{groups.map((g,i)=><div key={g.name}><g.icon size={22} strokeWidth={1.6}/><span>{g.name}</span><small dir="ltr">0{i+1}</small></div>)}</div>
 <div className="launch-privacy"><ShieldCheck size={19}/><p>این صفحه فقط معرفی و اعلام «به‌زودی» است. عضویت، دریافت اطلاعات شخصی، خرید و دسترسی به پنل‌ها از این لینک فعال نیست.</p></div>
 </section></main><footer className="launch-footer launch-container"><Brand compact/><span>پِتاو؛ برای همکاران، نه مصرف‌کنندهٔ نهایی.</span><button onClick={copyLink} className="launch-copy">{copied?<Check size={17}/>:<Copy size={17}/>} {copied?'لینک کپی شد':'کپی لینک صفحه'}</button></footer>{showLink&&<div className="launch-link-box" role="status"><label>لینک همین صفحه<input readOnly dir="ltr" value={currentPublicUrl()||'لینک زنده را از پیش‌نمایش عمومی باز کنید.'} onFocus={e=>e.target.select()}/></label><button className="launch-close-link" onClick={()=>setShowLink(false)}>بستن</button></div>}</div>
}
